export const sortSentenceData = {
  "s": [
    "The research findings demonstrate a substantial correlation between motivation and retention",
    "Effective academic writing requires coherence, precision, and carefully supported arguments",
    "Despite considerable opposition, the proposal was eventually adopted by the committee",
    "Learners benefit from analysing authentic texts rather than memorising isolated rules",
    "Frankly speaking, you could have handled it better",
    "Liam was walking a tightrope during the negotiations",
    "Not until the end did he realize the truth",
    "Lucas—as far as I can tell—was unaware of the changes",
    "The theory proposed by Emma gained substantial recognition",
    "To put it differently, Sophia needs more time",
    "From a formal perspective, your response was appropriate",
    "The implications of the data were meticulously analyzed by me",
    "To sum up, Jack will lead the team",
    "Seldom have you seen such a spectacular view",
    "The decision, controversial as it seemed, benefited Jack",
    "Olivia finally spilled the beans during the meeting",
    "The notion that they might be responsible is unfounded",
    "I made a compelling argument during the debate",
    "Despite the criticism—harsh though it was—he remained calm",
    "According to the findings, Emma should reconsider the hypothesis",
    "In essence, what I meant was quite clear",
    "It was a blessing in disguise that Liam missed the flight",
    "Jack laid out all the necessary points persuasively",
    "Jack demonstrated a nuanced understanding of the topic",
    "Emma is skating on thin ice with that decision",
    "Sophia had planned everything. Nevertheless, things went wrong",
    "Emily submitted the report. In contrast, the others delayed theirs",
    "If I were Jack's manager, I would act differently",
    "We were exhausted. Even so, we continued working",
    "The proposal opened a can of worms for Liam",
    "Rarely does Clara shy away from addressing contentious issues",
    "Had Ethan not underestimated the challenge, he would have prepared better",
    "No sooner had Mia presented her findings than the board approved the plan",
    "Under no circumstances would Leo divulge proprietary information",
    "Not only is Zoe adept at multitasking, but she also inspires her team",
    "Should Ava encounter any obstacles, she's well-equipped to overcome them",
    "In the unlikely event that Noah resigns, the company would face a setback",
    "Far from being conclusive, the evidence raised more questions than answers",
    "Were Ruby to take a more diplomatic approach, she'd win more allies",
    "Hardly had Finn begun his speech when the audience erupted in applause",
    "Contrary to popular belief, Ivy's strategy proved remarkably effective",
    "Be that as it may, Harper's decision sparked heated debate",
    "Much as Caleb respects tradition, he advocates for innovation",
    "Only by scrutinizing the data did Nora uncover the discrepancy",
    "Lest Max overlook critical details, he double-checked his calculations",
    "Such was Chloe's eloquence that her argument swayed the skeptics",
    "In hindsight, Theo should have delegated the task to a specialist",
    "No matter how persuasive Luna's pitch was, the investors remained unconvinced",
    "Provided that Ezra maintains his focus, he'll meet the deadline",
    "But for Violet's timely intervention, the project would have derailed",
    "Scarcely had Reid concluded his report when new data emerged",
    "As compelling as Quinn's proposal was, it lacked a practical implementation plan",
    "Were Sage to embrace constructive criticism, her work would improve significantly",
    "On no account should Wren compromise on ethical standards",
    "By no means was Elise's success attributable to luck alone",
    "Had Gideon not misjudged the market, his startup would have thrived",
    "In the event that Ada steps down, a succession plan is in place",
    "So intricate was Rory's design that it baffled even the experts",
    "Unless Esme refines her approach, she risks alienating her audience",
    "Not until Jude grasped the nuances did he appreciate the complexity",
    "Even though Lila faced skepticism, she persevered with her vision",
    "Such is Kiera's reputation that her endorsement carries significant weight",
    "As far as Tessa is concerned, the policy needs a complete overhaul",
    "No sooner had Silas submitted his proposal than it was rejected",
    "In lieu of concrete evidence, Aria's claims remain speculative",
    "Were Finn to adopt a more collaborative stance, the team would benefit",
    "Much to Piper's chagrin, her recommendations were largely ignored",
    "Only through meticulous planning did Hugo avert a crisis",
    "Be it ever so challenging, Rowan refuses to abandon his principles",
    "Had Aurora anticipated the backlash, she might have softened her tone",
    "By and large, Chloe's leadership has galvanized the department",
    "Lest Levi misinterpret the brief, he sought clarification upfront",
    "Such was Ezra's tenacity that he overcame formidable odds",
    "In the absence of consensus, Sienna opted for a compromise",
    "No matter how daunting the task, Tessa tackles it with resolve",
    "Provided that Violet adheres to the guidelines, her project will succeed",
    "Far from being deterred, Reid redoubled his efforts after the setback",
    "Were Lila to leverage her network, she could secure more funding",
    "On the premise that Kiera delivers results, she'll earn a promotion",
    "Scarcely had Finn launched the campaign when it went viral",
    "But for Aria's foresight, the team would have missed the deadline",
    "As astute as Piper's observations were, they went unheeded",
    "In retrospect, Hugo should have sought external expertise",
    "Even if Rowan faces resistance, he remains steadfast in his convictions",
    "Such is Tessa's expertise that her advice is rarely questioned",
    "Unless Silas addresses the flaws, his argument will lack credibility",
    "Not only did Aurora navigate the crisis, but she also earned acclaim",
    "In the face of adversity, Chloe maintained her composure",
    "Had Levi not acted swiftly, the opportunity would have slipped away",
    "By no stretch of the imagination could Ezra's plan be deemed feasible",
    "So profound was Sienna's insight that it reshaped the discussion",
    "Were Violet to refine her delivery, she'd captivate her audience",
    "On no account would Lila tolerate unethical behavior",
    "Much as Finn values stability, he's open to calculated risks",
    "Only by embracing change did Aria stay ahead of the curve",
    "Lest Piper overlook key metrics, she reviewed the data thoroughly",
    "Such was Hugo's charisma that he rallied the entire team",
    "In the event that Rowan falters, a contingency plan is ready",
    "Even if Hugo faces setbacks, he remains undeterred.",
    "Such was Rowan's innovation that it redefined industry standards.",
    "Provided that Tessa meets expectations, she'll earn the contract."
  ]
};
