export const sortSentenceData = {
  "s": [
    "Jack plays soccer every weekend",
    "I drink water after breakfast",
    "She reads a book at night",
    "They are happy in class",
    "Jack plays soccer every weekend",
    "We live in sunny Boston",
    "They run fast in races",
    "I like blue cars",
    "Lily eats ice cream happily",
    "I love my playful dog",
    "Sophie draws a shiny star",
    "We will swim in the pool",
    "The store opens early every day",
    "Ethan eats cereal every morning",
    "The cat feels soft and fluffy",
    "My shoes look brand new",
    "The window stays open all day",
    "I see a butterfly today",
    "He dances at the party",
    "We read a fun story",
    "The chair feels hard but sturdy",
    "The room looks small and cozy",
    "The tree grows tall and strong",
    "I will adopt a puppy",
    "Mason bought a toy today",
    "The fish swims fast in water",
    "I like warm sunny days",
    "My brother is called Jack",
    "We will plant flowers soon",
    "The bag is black and heavy",
    "Harper eats chocolate every day",
    "The horse gallops very fast",
    "I eat lunch at noon",
    "The sky looks clear and blue",
    "The house is big and warm",
    "My friend is named Noah",
    "The table is round and clean",
    "We will visit the beach",
    "I like to sing every day",
    "The room is very clean",
    "My sister is my best friend",
    "The building looks tall and modern",
    "The lion roars very loudly",
    "The park looks green and lively",
    "My mom is named Sarah",
    "I am drawing a heart today",
    "He eats pizza every day",
    "Will Jack play soccer tomorrow?",
    "Do you eat an apple?",
    "Is the dog barking at strangers?",
    "Do we live in Boston?",
    "Are they running fast today?",
    "Do you like blue cars?",
    "Is the sun shining brightly now?",
    "Will Lily eat ice cream?",
    "Do we visit the zoo?",
    "Can a bird fly above the trees?",
    "Do you see a tree?",
    "Will Ava run quickly tomorrow?",
    "Will he wear a jacket?",
    "Do you love my dog?",
    "Is the flower blooming now?",
    "Will we walk to the park?",
    "Do you want a cookie?",
    "Is my sister named Emma?",
    "Do you write letters?",
    "Does Liam ride a bike?",
    "Will we swim in the pool?",
    "Do you need a pencil?",
    "Is the store open every day?",
    "Does Olivia listen to music?",
    "Is the cat soft and fluffy?",
    "Is the road very long?",
    "Are my shoes brand new?",
    "Is the window open all day?",
    "Do you see a butterfly?",
    "Does he dance at the party?",
    "Do we read fun stories?",
    "Is the chair hard but sturdy?",
    "Will the tree grow tall and strong?",
    "Will I adopt a puppy?",
    "Does Charlotte wear a dress?",
    "Does Mason buy a toy?",
    "Do we clean the house?",
    "Do you like sunny days?",
    "Is my brother called Jack?",
    "Do you paint the wall?",
    "Does Ava talk to friends?",
    "Does Lucas kick the ball?",
    "Will we plant flowers soon?",
    "Can you find my keys?",
    "Is the door closed all day?",
    "Is the shirt blue?",
    "Is the bag black and heavy?",
    "Do you stay at home?",
    "Does he run in the park?",
    "Do we watch a movie?",
    "Is the horse strong and fast?",
    "Is the sky clear and blue?",
    "Is my friend named Noah?",
    "Is the table round and clean?",
    "Does Emily write a note?",
    "Will we visit the beach?",
    "Is the dog very friendly today?",
    "Do you like to sing?",
    "Is the room very clean?",
    "Is my sister my best friend?",
    "Emma does not read books every day",
    "Jack will not play soccer tomorrow",
    "I did not eat an apple",
    "Sarah does not have a cat",
    "We do not live in Boston",
    "They are not running fast today",
    "I do not like blue cars",
    "The sun is not shining brightly now",
    "Lily will not eat ice cream",
    "We did not visit the zoo",
    "This bird cannot fly above the trees",
    "I did not see a tree",
    "Ava will not run quickly tomorrow",
    "I do not love my dog",
    "The flower is not blooming now",
    "We will not walk to the park",
    "I did not want a cookie",
    "The house does not look big and cozy",
    "My sister is not named Emma",
    "I did not write a letter",
    "Sophie does not draw shiny stars",
    "Liam did not ride a bike",
    "We will not swim in the pool",
    "The clock does not tick loudly",
    "I did not need a pencil",
    "The store is not open every day",
    "Olivia did not listen to music",
    "Ethan does not eat cereal every day",
    "The cat is not soft and fluffy",
    "The road is not very long",
    "My shoes are not brand new",
    "The window is not open all day",
    "I did not see a butterfly",
    "He did not dance at the party",
    "We do not read fun stories",
    "The room does not look small and cozy",
    "The tree will not grow tall and strong",
    "I will not adopt a puppy",
    "Charlotte did not wear a dress",
    "Mason did not buy a toy",
    "We did not clean the house",
    "The fish does not swim fast in water",
    "I do not like sunny days",
    "My brother is not called Jack",
    "The car does not drive fast and smoothly",
    "I did not paint the wall",
    "Ava did not talk to friends",
    "Lucas did not kick the ball",
    "We will not plant flowers soon",
    "I drink water every day",
    "Tom plays football on Sundays",
    "Anna likes her soft rabbit",
    "The dog runs in the park",
    "We eat pizza on Fridays",
    "They live in a big city",
    "I see a bright star",
    "The sun rises early today",
    "Mia loves her new bike",
    "He reads a fun comic",
    "The sky is gray today",
    "We go to the beach",
    "A bird sings in the tree",
    "Zoe will dance tomorrow",
    "She wears a green hat",
    "We play games at night",
    "The moon shines at night",
    "I like my funny cat",
    "A flower grows in the garden",
    "Ben draws a big house",
    "We will visit the museum",
    "The baby smiles every day",
    "The room is warm today",
    "My brother is named Liam",
    "The dog jumps very high",
    "I read a short story",
    "Ella paints a red flower",
    "Sam rides a horse every week",
    "We will run in the park",
    "The clock shows ten o’clock",
    "I want a new book",
    "The shop closes at six",
    "Luke listens to fun songs",
    "Ava eats an orange every day",
    "The cat sleeps on the chair",
    "I drink tea in the evening",
    "The street is very quiet",
    "My bag is small and red",
    "The door opens every morning",
    "I see a white cloud",
    "He sings at school",
    "We write a new story",
    "The apple tastes very sweet",
    "The table is big and brown",
    "The house looks small today",
    "A tree stands in the yard",
    "I will buy a dog",
    "Noah takes a fun photo",
    "We washed the car today",
    "The fish lives in a bowl",
    "I like cold rainy days",
    "The book is on the shelf",
    "My sister is called Mia",
    "The car stops at the light",
    "Zoe talked to her teacher",
    "Jack hits the ball softly",
    "We will draw a picture",
    "The baby cries every night",
    "The window is closed today",
    "The shirt is soft and new",
    "The box is heavy and blue",
    "Lily eats cookies every day",
    "He swims in the lake",
    "We see a new movie",
    "The cow eats grass every day",
    "I drink coffee at noon",
    "The house smells nice today",
    "My friend is named Ava",
    "The chair is small and red",
    "I see a yellow balloon",
    "Chloe writes a fun poem",
    "Tom drinks juice every morning",
    "We will go to the forest",
    "The dog looks happy today",
    "I like to dance every day",
    "The kitchen is very clean",
    "My mom is my friend",
    "The school looks big and new",
    "Ben reads a new magazine",
    "The tiger runs very fast",
    "The garden looks colorful today",
    "My dad is named Mark",
    "The train moves very fast",
    "I am making a star today",
    "Sophie walks to the shop",
    "He eats ice cream every day",
    "We bought a new toy",
    "Will Anna dance tomorrow?",
    "Do you drink water?",
    "Is the dog running now?",
    "Do we live in a city?",
    "Are they playing today?",
    "Do you like red balls?",
    "Is the sun rising now?",
    "Will Mia ride a bike?",
    "Does he read a comic?",
    "Do we go to the beach?",
    "Can a bird sing?",
    "Will Zoe dance tomorrow?",
    "Will she wear a hat?",
    "Do we play games?",
    "Do you like my cat?",
    "Is the flower growing now?",
    "Does Ben draw a house?",
    "Will we visit a museum?",
    "Did you eat bread today?",
    "Is my brother named Liam?",
    "Does the dog jump high?",
    "Do you read stories?",
    "Does Sam ride a horse?",
    "Will we run in the park?",
    "Do you want a book?",
    "Is the shop open now?",
    "Does Luke listen to songs?",
    "Is the cat sleeping now?",
    "Do you drink tea?",
    "Is the street quiet now?",
    "Are my bags small?",
    "Is the door open now?",
    "Do you see a cloud?",
    "Does he sing at school?",
    "Do we write stories?",
    "Is the apple sweet today?",
    "Is the table big?",
    "Will a tree grow tall?",
    "Will I buy a dog?",
    "Does Emma wear gloves?",
    "Does Noah take a photo?",
    "Do we wash the car?",
    "Do you like rainy days?",
    "Is the book on the shelf?",
    "Is my sister called Mia?",
    "Do you clean my room?",
    "Does Zoe talk to teachers?",
    "Does Jack hit the ball?",
    "Will we draw pictures?",
    "Is the baby crying today?",
    "Did you lose my pen?",
    "Is the window closed now?",
    "Is the shirt soft?",
    "Is the box heavy?",
    "Do you walk to school?",
    "Does he swim in the lake?",
    "Do we see a movie?",
    "Is the cow eating grass?",
    "Do you drink coffee?",
    "Is the sky clear today?",
    "Is my friend named Ava?",
    "Is the chair small?",
    "Do you see a balloon?",
    "Does Chloe write a poem?",
    "Does Tom drink juice?",
    "Will we go to the forest?",
    "Is the dog happy now?",
    "Do you like to dance?",
    "Is the kitchen clean?",
    "Is my mom my friend?",
    "Do you feel happy?",
    "I walk to the market",
    "Lily paints a green tree",
    "Max plays with his dog",
    "The cat jumps on the table",
    "We eat pasta on Mondays",
    "They sleep in a tent",
    "I hear a loud bell",
    "The rain falls softly today",
    "Zoe likes her yellow kite",
    "He writes a short note",
    "The cloud is white today",
    "We see a tall mountain",
    "A frog hops in the pond",
    "I hold a blue pen",
    "Ella will sing tomorrow",
    "She buys a red coat",
    "We draw pictures at school",
    "The stars twinkle at night",
    "I pet my soft hamster",
    "A butterfly lands on the flower",
    "Tom builds a small castle",
    "We will climb the hill",
    "The toddler laughs every day",
    "The yard is cool today",
    "The puppy chews a bone",
    "I watch a funny video",
    "Ava knits a warm scarf",
    "Luke sails a boat every week",
    "We will bike to the lake",
    "The lamp glows every night",
    "I need a new notebook",
    "The cafe opens at seven",
    "Mia watches birds every day",
    "Jack eats toast every morning",
    "The bird nests in the tree",
    "I sip coffee every afternoon",
    "The path is short and green",
    "My hat is big and black",
    "The gate opens every day",
    "I touch a smooth stone",
    "He jogs in the forest",
    "We plant seeds in spring",
    "The orange tastes very juicy",
    "The shelf is tall and white",
    "The cottage looks tiny today",
    "I will feed a kitten",
    "Emma picked a red apple",
    "We fixed the chair today",
    "The turtle walks very slowly",
    "I like windy autumn days",
    "The pencil is on the desk",
    "The bike moves very fast",
    "Lily called her grandma today",
    "Max throws the ball high",
    "The child claps every morning",
    "The mirror is clean today",
    "The jacket is warm and soft",
    "The basket is light and brown",
    "Ava eats strawberries every day",
    "He hikes in the hills",
    "We heard a new song",
    "The goat climbs steep rocks",
    "I eat soup at dinner",
    "The air is fresh today",
    "The barn smells like hay",
    "The sofa is wide and gray",
    "I see a pink sunset",
    "Sophie typed a fun email",
    "Jack drinks lemonade every day",
    "We will skate on ice",
    "The horse looks strong today",
    "I like to read every night",
    "My dad is my hero",
    "The tower looks old and tall",
    "I feel tired this evening.",
    "Tom draws a fast car",
    "The bear sleeps in winter",
    "The field looks wide today",
    "My mom is named Lily",
    "The boat floats on water",
    "I folded a paper plane",
    "Zoe hopped to the park",
    "He eats burgers every day",
    "We find a shiny shell",
    "I drink milk every morning",
    "She plays tennis on weekends",
    "We live in a small village",
    "He likes red apples",
    "The cat sleeps on the sofa",
    "They walk to school every day",
    "I see a yellow bird",
    "The sun shines in the afternoon",
    "Anna loves her new shoes",
    "He reads a book at night",
    "The sky is blue today",
    "We go to the market on Saturdays",
    "A dog barks in the yard",
    "Tom will swim tomorrow",
    "She wears a purple dress",
    "We play cards in the evening",
    "The moon is bright tonight",
    "I like my black bicycle",
    "A flower grows in the pot",
    "Ben draws a small car",
    "We will visit grandma soon",
    "The baby laughs every day",
    "The kitchen is clean today",
    "My sister is named Clara",
    "The horse runs in the field",
    "I write a letter every week",
    "Ella paints a blue sky",
    "Sam rides a bike every day",
    "We will dance at the party",
    "The clock shows eight o’clock",
    "I want a green hat",
    "The shop opens at ten",
    "Lily watches TV every evening",
    "Jack eats bread every morning",
    "The bird flies above the tree",
    "I drink juice at lunch",
    "The street is quiet at night",
    "My bag is big and blue",
    "The door closes every evening",
    "I see a red balloon",
    "He sings in the choir",
    "We write stories at school",
    "The banana tastes sweet",
    "The table is long and white",
    "The house looks new today",
    "A tree grows in the garden",
    "I will buy a kitten",
    "Mia picks a pink flower",
    "We clean the room today",
    "The fish swims in the tank",
    "I like sunny days",
    "The book is on the table",
    "My brother is named Alex",
    "The car parks in the garage",
    "Zoe talks to her friend",
    "Max kicks a soccer ball",
    "We will paint the fence",
    "The baby sleeps at noon",
    "The window is open today",
    "The shirt is clean and green",
    "The box is small and brown",
    "Anna loves strawberries",
    "He runs in the park",
    "We see a funny movie",
    "The cow eats grass in the field",
    "I drink water at dinner",
    "The room smells fresh today",
    "My friend is named Leo",
    "The chair is soft and red",
    "I see a white cloud",
    "Chloe writes a short story",
    "Tom drinks coffee every morning",
    "We will go to the zoo",
    "The dog looks happy today",
    "I like to read books",
    "The bathroom is clean",
    "My mom is my friend",
    "The school looks big today",
    "Ben reads a comic book",
    "The tiger sleeps in the shade",
    "The park looks green today",
    "My dad is named Paul",
    "The bus arrives at seven",
    "I make a paper boat",
    "Sophie walks to the library",
    "He likes chocolate ice cream",
    "We buy a new lamp",
    "Will Anna play tennis tomorrow?",
    "Do you drink milk?",
    "Is the cat sleeping now?",
    "Do we live in a village?",
    "Are they walking to school?",
    "Do you like red apples?",
    "Is the sun shining today?",
    "Will Tom swim tomorrow?",
    "Does he read a book?",
    "Do we go to the market?",
    "Can a dog bark loudly?",
    "Will Zoe wear a dress?",
    "Will she play cards?",
    "Do we like bicycles?",
    "Do you see a flower?",
    "Is the bird flying now?",
    "Does Ben draw a car?",
    "Will we visit grandma?",
    "Did you eat bread today?",
    "Is my sister named Clara?",
    "Does the horse run fast?",
    "Do you write letters?",
    "Does Ella paint pictures?",
    "Will we dance at the party?",
    "Do you want a hat?",
    "Is the shop open now?",
    "Does Lily watch TV?",
    "Is the bird in the tree?",
    "Do you drink juice?",
    "Is the street quiet now?",
    "Is my bag big?",
    "Is the door closed?",
    "Do you see a balloon?",
    "Does he sing in the choir?",
    "Do we write stories?",
    "Is the banana sweet?",
    "Is the table long?",
    "Will a tree grow tall?",
    "Will I buy a kitten?",
    "Does Mia pick flowers?",
    "Do we clean the room?",
    "Do you like sunny days?",
    "Is the book on the table?",
    "Is my brother named Alex?",
    "Do you talk to friends?",
    "Does Max kick a ball?",
    "Will we paint the fence?",
    "Does the baby sleep?",
    "Is the window open?",
    "Is the shirt clean?",
    "Is the box small?",
    "Do you stay at home?",
    "Does he run in the park?",
    "Do we see a movie?",
    "Is the cow eating grass?",
    "Do you drink water?",
    "Is my friend named Leo?",
    "Is the chair soft?",
    "Do you see a cloud?",
    "Does Chloe write stories?",
    "Does Tom drink coffee?",
    "Will we go to the zoo?",
    "Is the dog happy?",
    "Do you like to read?",
    "Is the bathroom clean?",
    "Is my mom my friend?",
    "Do you feel happy?",
    "I walk to the park",
    "Lily paints a red house",
    "Max plays with a kite",
    "The dog jumps on the bed",
    "We eat salad on Tuesdays",
    "They swim in the pool",
    "I hear a loud noise",
    "The rain falls in the evening",
    "Zoe likes her blue scarf",
    "He writes a long email",
    "The hill is green today",
    "We climb a tall tree",
    "A butterfly flies in the garden",
    "I carry a small bag",
    "Ella will draw tomorrow",
    "She buys a yellow coat",
    "We sing songs at school",
    "The stars shine at night",
    "I feed my goldfish",
    "A leaf falls from the tree",
    "Jack builds a toy plane",
    "We will ride bicycles",
    "The girl smiles every day",
    "My friend is named Emma",
    "Lily sews a blue pillow",
    "Tom catches a ball",
    "We will hike in the forest",
    "The fan spins every day",
    "I want a new pencil",
    "The library opens at nine",
    "Noah eats a pear every day",
    "The mouse runs in the house",
    "I drink tea every night",
    "The bridge is old and long",
    "My coat is warm and black",
    "The light turns on at dusk",
    "I smell a fresh orange",
    "He rides a skateboard every day",
    "We collect coins at home",
    "The rug is soft and blue",
    "The cabin looks small today",
    "A vine grows on the fence",
    "I will hug my dog",
    "Max finds a shiny stone",
    "We are painting the wall today",
    "The duck swims in the pond",
    "I like snowy days",
    "The lamp is on the desk",
    "The truck stops at the shop",
    "Ella is calling her mom today",
    "Sam kicks a soft ball",
    "The boy waves every morning",
    "The curtain is closed today",
    "The sweater is warm and red",
    "The tray is light and white",
    "Zoe loves bananas",
    "He rows a boat on Sundays",
    "We taste a new soup",
    "The sheep eats grass every day",
    "I drink juice at breakfast",
    "My classmate is named Mia",
    "The bed is soft and wide",
    "I see a bright sunrise",
    "Ava writes a short letter",
    "Noah drinks milk every evening",
    "We will jog in the park",
    "The rabbit looks soft today",
    "I like to paint pictures",
    "My grandma is my friend",
    "Jack reads a fun book",
    "The wolf runs in the forest",
    "The meadow looks green today",
    "My dad is named John",
    "The plane flies in the sky",
    "I make a paper star",
    "Zoe jumps in the park",
    "He eats pizza every day",
    "We find a small shell",
    "Will Max play with a kite?",
    "Do you walk to the park?",
    "Is the dog jumping now?",
    "Do we eat salad every day?",
    "Are they swimming in the pool?",
    "Do you hear a noise?",
    "Is the rain falling now?",
    "Will Zoe wear a scarf?",
    "Does he write emails?",
    "Do we climb a tree?",
    "Is the butterfly flying now?",
    "Do you carry a bag?",
    "Will Ella draw tomorrow?",
    "Will she buy a coat?",
    "Do we sing songs?",
    "Do you feed a fish?",
    "Is the leaf falling now?",
    "Does Jack build a plane?",
    "Will we ride bicycles?",
    "Will you eat salad today?",
    "Is my friend named Emma?",
    "Does the cat climb trees?",
    "Do you listen to music?",
    "Does Tom catch a ball?",
    "Will we hike in the forest?",
    "Do you want a pencil?",
    "Is the library open now?",
    "Does Noah eat a pear?",
    "Is the mouse running now?",
    "Did you drink tea today?",
    "Is the bridge old?",
    "Is my coat warm?",
    "Is the light on now?",
    "Do you smell an orange?",
    "Does he ride a skateboard?",
    "Do we collect coins?",
    "Is the banana soft?",
    "Is the rug soft?",
    "Will a vine grow tall?",
    "Will I hug my dog?",
    "Does Max find a stone?",
    "Do we paint the wall?",
    "Do you like snowy days?",
    "Is the lamp on the desk?",
    "Do you call your mom?",
    "Does Sam kick a ball?",
    "Is the boy waving?",
    "Is the curtain closed?",
    "Is the sweater warm?",
    "Is the tray light?",
    "Do you rest at home?",
    "Does he row a boat?",
    "Do we taste soup?",
    "Is the sheep eating grass?",
    "Do you drink juice?",
    "Is my classmate named Mia?",
    "Is the bed soft?",
    "Do you see a sunrise?",
    "Does Ava write letters?",
    "Does Noah drink milk?",
    "Will we jog in the park?",
    "Is the rabbit soft?",
    "Do you like to paint?",
    "Is my grandma my friend?",
    "I do not drink coffee",
    "She does not play tennis",
    "We do not live in a city",
    "He does not like apples",
    "The cat does not sleep here",
    "They do not walk to school",
    "I do not see a bird",
    "The sun is not shining now",
    "Anna does not love shoes",
    "He does not read books",
    "The sky is not gray today",
    "We do not go to the market",
    "The dog is not barking now",
    "Tom will not swim tomorrow",
    "She does not wear dresses",
    "We do not play cards",
    "The moon is not bright now",
    "I do not like bicycles",
    "The flower does not grow",
    "Ben does not draw cars",
    "We will not visit grandma",
    "The baby does not laugh",
    "The kitchen is not clean",
    "My sister is not Clara",
    "The horse does not run",
    "I do not write letters",
    "Ella does not paint today",
    "Sam does not ride a bike",
    "We will not dance tonight",
    "The clock is not correct",
    "I do not want a hat",
    "The shop is not open",
    "Lily does not watch TV",
    "Jack does not eat bread",
    "The bird is not in the tree",
    "I do not drink juice",
    "The street is not quiet",
    "My bag is not big",
    "The door is not closed",
    "I do not see a balloon",
    "He does not sing songs",
    "We do not write stories",
    "The banana is not sweet",
    "The table is not long",
    "The house is not new",
    "The tree does not grow",
    "I will not buy a kitten",
    "Mia does not pick flowers",
    "We do not clean rooms",
    "The fish is not swimming",
    "I do not like sunny days",
    "The book is not on the table",
    "My brother is not Alex",
    "The car is not parked here",
    "Zoe is not talking today",
    "Max does not kick a ball",
    "We will not paint the fence",
    "The baby does not sleep",
    "The window is not open",
    "The shirt is not clean",
    "The box is not small",
    "Anna does not love strawberries",
    "He does not run today",
    "We do not see a movie",
    "The cow does not eat grass",
    "I do not drink water",
    "The room does not smell fresh",
    "My friend is not Leo",
    "The chair is not soft",
    "I do not see a cloud",
    "Chloe does not write stories",
    "Tom does not drink coffee",
    "We will not go to the zoo",
    "The dog is not happy",
    "I do not like to read",
    "The bathroom is not clean",
    "My mom is not my friend",
    "The school is not big",
    "Ben does not read comics",
    "The tiger does not sleep",
    "The park is not green",
    "My dad is not Paul",
    "The bus is not here",
    "I do not make boats",
    "Sophie is not walking today",
    "He does not like ice cream",
    "We do not buy lamps",
    "I eat breakfast every morning",
    "Tom plays basketball on Fridays",
    "We live in a big town",
    "She likes green pears",
    "The dog sleeps in the garden",
    "They ride bicycles to school",
    "I see a small frog",
    "The sun rises early today",
    "Mia loves her red bag",
    "He watches a movie at night",
    "The sky is clear today",
    "We visit the zoo on Sundays",
    "A cat runs in the yard",
    "Anna will read a book tomorrow",
    "She wears a blue jacket",
    "We play games in the afternoon",
    "The stars are bright tonight",
    "I like my white shoes",
    "A plant grows in the garden",
    "Ben draws a tall tree",
    "We will go to the beach soon",
    "The baby smiles every morning",
    "The living room is tidy today",
    "My brother is named Leo",
    "The bird sings in the tree",
    "I write a note every day",
    "Ella paints a red flower",
    "Sam walks to the park every day",
    "We will sing at school",
    "The clock shows nine o’clock",
    "I want a yellow pencil",
    "The bakery opens at eight",
    "Zoe listens to songs every day",
    "Jack eats cereal every morning",
    "The fish swims in the bowl",
    "I drink water in the evening",
    "The road is long and quiet",
    "My backpack is heavy and green",
    "The gate opens every morning",
    "I see a pink butterfly",
    "He plays the piano at home",
    "We read books at school",
    "The orange tastes juicy",
    "The chair is small and white",
    "The house looks cozy today",
    "A flower blooms in the yard",
    "I will feed my hamster",
    "Lily picks a green apple",
    "We are cleaning the kitchen today",
    "The turtle walks slowly",
    "I like rainy days",
    "The notebook is on the desk",
    "My sister is named Emma",
    "The car stops at the light",
    "Chloe talks to her teacher",
    "Max throws a soft ball",
    "We will draw pictures soon",
    "The baby sleeps in the crib",
    "The window is closed today",
    "The shirt is soft and blue",
    "The basket is light and brown",
    "Ava eats cherries every day",
    "He jogs in the park",
    "We hear a funny song",
    "The horse eats grass in the field",
    "I drink tea at breakfast",
    "The air smells fresh today",
    "My friend is named Noah",
    "The sofa is big and red",
    "I see a gray cloud",
    "Sophie writes a fun poem",
    "Tom drinks juice every morning",
    "We will visit the farm",
    "The dog looks friendly today",
    "I like to draw pictures",
    "The bedroom is clean today",
    "My dad is my best friend",
    "The school is old and big",
    "Ben reads a story every night",
    "The lion roars in the zoo",
    "The garden looks colorful today",
    "My mom is named Sarah",
    "The train arrives at six",
    "I make a paper plane",
    "Clara runs to the shop",
    "He likes vanilla ice cream",
    "We buy a new book",
    "Will Tom play basketball tomorrow?",
    "Do you eat breakfast?",
    "Is the dog sleeping now?",
    "Do we live in a town?",
    "Are they riding bicycles?",
    "Do you like green pears?",
    "Is the sun rising now?",
    "Will Anna read a book?",
    "Does she wear a jacket?",
    "Do we visit the zoo?",
    "Can a cat run fast?",
    "Will Zoe play games?",
    "Do you like white shoes?",
    "Do you see a plant?",
    "Is the bird singing now?",
    "Does Ben draw a tree?",
    "Will we go to the beach?",
    "Did you eat cereal today?",
    "Is my brother named Leo?",
    "Does the bird sing loudly?",
    "Do you write notes?",
    "Does Ella paint flowers?",
    "Will we sing at school?",
    "Do you want a pencil?",
    "Is the bakery open now?",
    "Does Zoe listen to songs?",
    "Is the fish swimming now?",
    "Do you drink water?",
    "Is the road quiet today?",
    "Is my backpack heavy?",
    "Is the gate open now?",
    "Do you see a butterfly?",
    "Does he play the piano?",
    "Do we read books?",
    "Is the orange juicy?",
    "Is the chair small?",
    "Will a flower bloom soon?",
    "Will I feed my hamster?",
    "Does Lily pick apples?",
    "Do we clean the kitchen?",
    "Do you like rainy days?",
    "Is the notebook on the desk?",
    "Is my sister named Emma?",
    "Does the car stop here?",
    "Does Chloe talk to teachers?",
    "Does Max throw a ball?",
    "Will we draw pictures?",
    "Is the baby sleeping now?",
    "Is the window closed?",
    "Is the shirt soft?",
    "Is the basket light?",
    "Do you love cherries?",
    "Does he jog in the park?",
    "Do we hear a song?",
    "Is the horse eating grass?",
    "Do you drink tea?",
    "Is my friend named Noah?",
    "Is the sofa big?",
    "Do you see a cloud?",
    "Does Sophie write poems?",
    "Does Tom drink juice?",
    "Will we visit the farm?",
    "Is the dog friendly?",
    "Do you like to draw?",
    "Is the bedroom clean?",
    "Is my dad my friend?",
    "Is the school old?",
    "Does Ben read stories?",
    "Is the lion roaring now?",
    "Is the garden colorful?",
    "Is my mom named Sarah?",
    "Does the train arrive soon?",
    "Do you make a plane?",
    "Does Clara run to the shop?",
    "Does he like ice cream?",
    "Do we buy a book?",
    "I do not eat candy",
    "Tom does not play soccer",
    "We do not live in a city",
    "She does not like pears",
    "The dog does not sleep inside",
    "They do not ride bicycles",
    "I do not see a frog",
    "The sun is not shining now",
    "Mia does not love bags",
    "He does not watch movies",
    "The sky is not cloudy today",
    "We do not visit the zoo",
    "The cat does not run here",
    "Anna will not read tomorrow",
    "She does not wear jackets",
    "We do not play games",
    "The stars are not bright now",
    "I do not like shoes",
    "The plant does not grow",
    "Ben does not draw trees",
    "We will not go to the beach",
    "The baby does not smile",
    "The living room is not tidy",
    "My brother is not Leo",
    "The bird does not sing",
    "I do not write notes",
    "Ella does not paint today",
    "Sam does not walk to the park",
    "We will not sing at school",
    "The clock is not working",
    "I do not want a pencil",
    "The bakery is not open",
    "Zoe does not listen to songs",
    "Jack does not eat cereal",
    "The fish is not swimming",
    "I do not drink water now",
    "The road is not quiet",
    "My backpack is not heavy",
    "The gate is not open",
    "I do not see a butterfly",
    "He does not play the piano",
    "We do not read books",
    "The orange is not juicy",
    "The chair is not small",
    "The house is not cozy",
    "The flower does not bloom",
    "I will not feed my hamster",
    "Lily does not pick apples",
    "We do not clean the kitchen",
    "The turtle is not fast",
    "I do not like rainy days",
    "The notebook is not on the desk",
    "My sister is not Emma",
    "The car does not stop here",
    "Chloe is not talking today",
    "Max does not throw balls",
    "We will not draw pictures",
    "The baby is not sleeping",
    "The window is not closed",
    "The shirt is not soft",
    "The basket is not light",
    "Ava does not love cherries",
    "He is not jogging today",
    "We do not hear songs",
    "The horse does not eat grass",
    "I do not drink tea",
    "The air does not smell fresh",
    "My friend is not Noah",
    "The sofa is not big",
    "I do not see a cloud",
    "Sophie does not write poems",
    "Tom does not drink juice",
    "We will not visit the farm",
    "The dog is not friendly",
    "I do not like to draw",
    "The bedroom is not clean",
    "My dad is not at home",
    "The school is not big",
    "Ben does not read stories",
    "The lion is not roaring",
    "The garden is not colorful",
    "My mom is not Sarah",
    "The train is not here",
    "I do not make planes",
    "Clara is not running today",
    "He does not like ice cream",
    "We do not buy books",
    "I walk to the store",
    "Lily paints a blue bird",
    "Max plays with a toy car",
    "The cat jumps on the table",
    "We eat pasta on Mondays",
    "They swim in the lake",
    "I find a shiny coin",
    "The rain stops in the afternoon",
    "Zoe likes her green hat",
    "He writes a short story",
    "The hill is steep today",
    "We climb a small mountain",
    "A bee buzzes in the garden",
    "I carry a light bag",
    "Ella will sing tomorrow",
    "She buys a red scarf",
    "We watch birds in the park",
    "The lamp shines at night",
    "I brush my little cat",
    "A cloud floats in the sky",
    "Jack builds a sandcastle",
    "We will clean the yard",
    "The boy runs every morning",
    "My friend is named Ava",
    "Lily sews a small blanket",
    "Tom catches a butterfly",
    "We will hike in the woods",
    "The fan turns on every day",
    "I want a new notebook",
    "The library opens at ten",
    "Noah eats a banana every day",
    "The mouse hides in the box",
    "I drink milk every night",
    "The bridge is short and old",
    "My coat is warm and red",
    "The light glows every evening",
    "I smell a sweet rose",
    "He rides a scooter every day",
    "We collect shells at the beach",
    "The rug is soft and green",
    "The cabin looks tiny today",
    "A vine grows on the wall",
    "I will hug my puppy",
    "Max finds a lost key",
    "We are painting the door today",
    "The duck floats on the pond",
    "I like snowy winter days",
    "The lamp is on the table",
    "The truck parks at the store",
    "Ella is texting her friend today",
    "Sam kicks a red ball",
    "The girl giggles every day",
    "The curtain is open today",
    "The sweater is thick and blue",
    "The tray is light and silver",
    "Zoe eats oranges every day",
    "He rows a boat every week",
    "We taste a new cake",
    "The sheep eats grass every day",
    "I drink juice at lunch",
    "My classmate is named Tom",
    "The bed is wide and soft",
    "I see a golden sunrise",
    "Ava types a short email",
    "Noah sips tea every morning",
    "We will jog by the river",
    "The rabbit looks fluffy today",
    "I like to paint every day",
    "My grandma is my friend",
    "Jack reads a new magazine",
    "The wolf howls at night",
    "The meadow looks bright today",
    "My dad is named Mark",
    "The boat sails on the lake",
    "I fold a paper star",
    "Zoe hops in the yard",
    "He eats burgers every day",
    "We find a shiny shell",
    "Will Max play with a toy car?",
    "Do you walk to the store?",
    "Is the cat jumping now?",
    "Do we eat pasta every day?",
    "Are they swimming in the lake?",
    "Do you find coins?",
    "Is the rain stopping now?",
    "Will Zoe wear a hat?",
    "Does he write a story?",
    "Do we climb a mountain?",
    "Can a bee buzz?",
    "Do you carry a bag?",
    "Will Ella sing tomorrow?",
    "Will she buy a scarf?",
    "Do we watch birds?",
    "Do you brush your cat?",
    "Is the cloud floating now?",
    "Does Jack build a sandcastle?",
    "Will we clean the yard?",
    "Is the boy running now?",
    "Is my friend named Ava?",
    "Does Lily sew a blanket?",
    "Does Tom catch butterflies?",
    "Will we hike in the woods?",
    "Do you want a notebook?",
    "Is the library open now?",
    "Does Noah eat a banana?",
    "Is the mouse hiding now?",
    "Did you drink milk today?",
    "Is the bridge old?",
    "Is my coat warm?",
    "Is the light on now?",
    "Do you smell a rose?",
    "Does he ride a scooter?",
    "Do we collect shells?",
    "Is the rug soft?",
    "Is the cabin tiny?",
    "Will a vine grow tall?",
    "Will I hug my puppy?",
    "Does Max find a key?",
    "Do we paint the door?",
    "Do you like winter days?",
    "Is the lamp on the table?",
    "Does Ella text her friend?",
    "Does Sam kick a ball?",
    "Is the girl giggling now?",
    "Is the curtain open?",
    "Is the sweater thick?",
    "Is the tray light?",
    "Do you love oranges?",
    "Does he row a boat?",
    "Do we taste a cake?",
    "Is the sheep eating grass?",
    "Do you drink juice?",
    "Is my classmate named Tom?",
    "Is the bed wide?",
    "Do you see a sunrise?",
    "Does Ava type an email?",
    "Does Noah sip tea?",
    "Will we jog by the river?",
    "Is the rabbit fluffy?",
    "Do you like to paint?",
    "Is my grandma my friend?"
  ]
};
