export const sortSentenceData = {
  "s": [
    "He has been working here for three years",
    "Neither Jack nor Emma wanted to leave early",
    "If it rains tomorrow, we will cancel the trip",
    "This is the book that I told you about",
    "I had never seen such a beautiful sunset before",
    "We have been studying English for two years",
    "The man who lives next door is a doctor",
    "They were watching TV when the lights went out",
    "She has just finished her homework",
    "I think it will snow tomorrow",
    "You should try to get more sleep",
    "She might come to the party later",
    "Neither of the answers was correct",
    "You do not need to bring anything",
    "We were walking when it started to rain",
    "It is important to take a break sometimes",
    "I am going to visit my grandparents this weekend",
    "The cake was made by my mom",
    "If I were you, I would apologize",
    "I have not seen him since last week",
    "You must wear a helmet when riding a bike",
    "Either you or your brother has to go",
    "There is too much noise in this room",
    "It had been raining all morning",
    "This is the place where we met",
    "She asked if I liked chocolate",
    "You look tired. You should rest.",
    "I will help you as soon as I finish this",
    "We have been waiting for over an hour",
    "He is the one who broke the window",
    "I do not know what she wants",
    "Not only did he win the race, but he also broke the record",
    "There is not enough time to explain everything",
    "She speaks Spanish as well as English",
    "I will call you when I arrive",
    "You ought to see a doctor",
    "The house was built in 1920",
    "She used to live in a small village",
    "They are planning to visit Italy next summer",
    "If you work harder, you will achieve your goals",
    "My cousin has just returned from Japan",
    "Unless we hurry, we will miss the train",
    "He has not decided what to do next",
    "They were arguing about something unimportant",
    "He might be working late tonight",
    "We have never been to that restaurant before",
    "Could you explain this again, please?",
    "She did not remember locking the door",
    "We were having dinner when it started snowing",
    "I do not know if she will agree",
    "You should not talk during the movie",
    "She always brings snacks to the meeting",
    "We need to discuss the new proposal",
    "He was injured while playing football",
    "I wonder how they solved the problem",
    "Have you heard anything from him recently?",
    "She speaks more clearly than her sister",
    "This book is more interesting than the last one",
    "He promised he would be careful",
    "I was not sure whether to laugh or cry",
    "She told me not to be late",
    "They might have forgotten the appointment",
    "Why do not we take a break now?",
    "This song reminds me of my childhood",
    "Let me know if anything changes",
    "He managed to fix the broken chair",
    "Would you like something to drink?",
    "I will call you when I get home",
    "He has been learning French for a year",
    "It is hard to understand his handwriting",
    "She refused to answer the question",
    "What would you do in my place?",
    "I had trouble finding the place",
    "Do you remember meeting her before?",
    "He got used to living alone",
    "The teacher explained it very well",
    "Is there anything I can help with?",
    "They decided to cancel the event",
    "Why did you leave so early?",
    "The road was blocked by snow",
    "I found it hard to believe",
    "Can you tell me the truth?",
    "I did not expect them to win",
    "What time does the movie start?",
    "She kept asking the same question",
    "He forgot to water the plants",
    "She was late because of traffic",
    "They rarely go out on weekdays",
    "He looks like his older brother",
    "Please remind me to call her",
    "I will not be able to join you",
    "We were surprised by the news",
    "It took me an hour to finish",
    "They have not finished their homework yet",
    "Can I ask you a question?",
    "We need to make a decision",
    "They offered us a great deal",
    "They were not aware of the danger",
    "This room needs to be cleaned",
    "He used to be my neighbor",
    "We stayed at a lovely hotel",
    "Have you finished reading the book?",
    "She warned us about the dog",
    "Do you think it will rain?",
    "I am not ready to leave yet",
    "You do not have to decide now",
    "I do not feel like going out",
    "Why are you looking at me?",
    "He did not mean to hurt you",
    "This jacket does not fit me anymore",
    "We have met once before, haven't we?",
    "She is always complaining about the weather",
    "Can we talk about it later?",
    "He is likely to be late again",
    "We had a great time yesterday",
    "He told me he was tired",
    "I can't believe she said that",
    "I am not used to this weather",
    "They insisted on paying the bill",
    "We are planning to move next year",
    "It is too late to change now",
    "I would love to join you sometime",
    "This was written by a student",
    "Do not forget to take your umbrella",
    "They might arrive earlier than expected",
    "She forgot where she put her keys",
    "We went hiking despite the rain",
    "He used to work in finance",
    "I do not have enough time right now",
    "Do you know how this works?",
    "She wants to become a designer",
    "The store opens at nine o'clock",
    "He suggested taking a different route",
    "They have not decided what to do",
    "I lost my wallet at the park",
    "She did not mean to be rude",
    "We should leave before it gets dark",
    "Have you checked your email today?",
    "It was colder than I expected",
    "We do not know what caused the problem",
    "They told us to wait outside",
    "I could not find what I needed",
    "The bus stopped in front of the school",
    "It looks like it is going to snow",
    "I will see you at the airport",
    "She helped me carry the bags",
    "Do you have time to talk?",
    "He is working on a new project",
    "Please let me know your answer",
    "It is not as easy as it seems",
    "Let's meet in front of the library",
    "She got a promotion last week",
    "I have never heard of that place",
    "We need to charge the battery",
    "I forgot to set the alarm",
    "They waited for more than an hour",
    "He was surprised by the results",
    "It was not as expensive as I thought",
    "She got a new phone yesterday",
    "It is difficult to say for sure",
    "We need to prepare for the worst",
    "They have been working together recently",
    "She refused to go with them",
    "I have to finish this by Friday",
    "This app is easy to use",
    "They are building a new shopping center",
    "I heard the news this morning",
    "You will need to bring your ID",
    "We took the train instead of flying",
    "I do not understand what you mean",
    "They live on the same street",
    "We had a lot of fun yesterday",
    "She got there just in time",
    "It started raining all of a sudden",
    "He left without taking his phone",
    "Do you want to come with us?",
    "She made a very good point",
    "He gave me a useful tip",
    "They usually eat out on Fridays",
    "He usually sits at the front",
    "She will not be able to attend",
    "The kids are watching a movie",
    "We had to wait in line",
    "Do you know his last name?",
    "We got stuck in traffic again",
    "I forgot to reply to her message",
    "The weather is getting warmer every day",
    "She bought a gift for her sister",
    "We walked through the old town",
    "He left before I could say goodbye",
    "We have known each other for years.",
    "She always takes the same route.",
    "I am not sure what to do.",
    "The class ended earlier than usual.",
    "Do you still live with your parents?",
    "She found the keys under the sofa.",
    "They stopped to take some photos.",
    "He gave a very long speech.",
    "She borrowed a dress from her friend.",
    "He spends a lot of time online.",
    "I did not hear what you said.",
    "She likes to walk in the rain.",
    "He forgot his wallet at home.",
    "They went camping in the mountains.",
    "I saw him crossing the street.",
    "I visited my aunt last weekend.",
    "Do you need any help with that?",
    "She tried to fix it herself.",
    "I usually go shopping on Sundays.",
    "We listened to music all night.",
    "She cleaned the kitchen after dinner.",
    "He arrived just before the bell rang.",
    "They opened a new café downtown.",
    "I like the way she thinks.",
    "SHe is not ready to decide yet.",
    "We ate dinner at a local place.",
    "He kept looking at his watch.",
    "The movie ended with a twist.",
    "I locked the door before leaving.",
    "They are having a baby next month.",
    "He likes to swim in the sea.",
    "I can meet you at the station.",
    "The exam was not as hard as expected.",
    "She dropped her phone in the sink.",
    "He helped me with the boxes.",
    "She lost her voice after the concert.",
    "He missed his flight by a minute.",
    "We watched a documentary last night.",
    "He was not sure how to answer.",
    "I saw a rainbow this morning.",
    "They went out for ice cream.",
    "He offered to drive us home.",
    "I felt tired after the trip.",
    "He wrote a note and left it.",
    "I am not allowed to stay out late.",
    "She was chosen for the role.",
    "I cleaned my room this morning.",
    "We were invited to the wedding.",
    "He likes to sing in the shower.",
    "I lost my phone on the bus.",
    "We visited a castle last summer.",
    "He forgot to lock the door.",
    "She drew a picture of her cat.",
    "We are leaving in an hour.",
    "I took a different route today.",
    "He did not show up on time.",
    "She gave him a handmade gift.",
    "I took a nap after lunch.",
    "She looked happy in the photo.",
    "We ran into each other downtown.",
    "She baked cookies for the team.",
    "They laughed at the funny story.",
    "We met at the coffee shop.",
    "I called the doctor this morning.",
    "We waited in a long line.",
    "They bought souvenirs from the trip.",
    "He listened carefully to the instructions.",
    "We watched the stars at night.",
    "They stayed at a bed and breakfast.",
    "She cut her finger while cooking.",
    "He made a cake from scratch.",
    "He borrowed a book from me.",
    "She walked her dog at sunset.",
    "We visited the museum on Friday.",
    "They planted flowers in the garden.",
    "I made a list of groceries.",
    "We shared a pizza for dinner.",
    "They joined us for the hike.",
    "I watered the plants this morning.",
    "They left early to avoid traffic.",
    "I reserved a table for two.",
    "We took a taxi to the airport.",
    "They cleaned the garage last weekend.",
    "She brushed her hair before leaving.",
    "He forgot to do his homework.",
    "I charged my phone last night.",
    "We packed our bags for the trip.",
    "He shared his notes with me.",
    "I printed the document at work.",
    "We finished the project on time.",
    "They searched for a parking spot.",
    "She stayed calm during the storm.",
    "He ironed his shirt before the interview.",
    "I painted a picture of the lake.",
    "We walked through the forest trail.",
    "She filled the glass with water.",
    "He closed the window before sleeping.",
    "I listened to my favorite playlist.",
    "We enjoyed the concert last night.",
    "He cleaned his shoes with a cloth.",
    "I boiled some water for tea.",
    "We visited a zoo last weekend.",
    "They sang along to the music.",
    "She tied a ribbon around the box.",
    "I watched the sunrise from my balcony.",
    "We walked to the bookstore together.",
    "They checked into the hotel at noon.",
    "I copied the notes from the board.",
    "We celebrated his birthday last night.",
    "They waited patiently for their turn.",
    "She forgot the name of the street.",
    "I mailed the letter this morning.",
    "We swept the floor before guests arrived.",
    "She arranged a surprise for him.",
    "I cleaned the table after lunch.",
    "We drew pictures in the sand.",
    "She called her mother every weekend.",
    "He left his bag on the bus.",
    "I filled out the form online.",
    "We turned the lights off at night.",
    "They listened to the guide carefully.",
    "She set the table for dinner.",
    "He wrapped the gift in blue paper.",
    "I added salt to the soup.",
    "We closed the store at 8 p.m.",
    "They washed their hands before eating.",
    "She turned in her assignment on time.",
    "He stayed at a friend's house last night.",
    "They visited their cousins in the countryside.",
    "We found a shortcut through the alley.",
    "He booked a flight to Chicago.",
    "They danced all evening at the wedding.",
    "We learned a new song in class.",
    "She fell asleep during the movie.",
    "We saw dolphins at the beach.",
    "He dropped his phone on the floor.",
    "She forgot to send the email.",
    "I cleaned out the closet today.",
    "We changed our seats at the theater.",
    "He cooked dinner for his parents.",
    "She listened to the radio on her way home.",
    "I washed the dishes after lunch.",
    "They visited the old castle on the hill.",
    "We sat under the big oak tree.",
    "She lost her necklace at the party.",
    "I shared my lunch with a friend.",
    "They watched a play at the theater.",
    "We borrowed a ladder from the neighbor.",
    "He watered the garden this morning.",
    "She took care of the baby.",
    "I saved the file to a USB drive.",
    "They climbed the mountain last weekend.",
    "We picked strawberries at the farm.",
    "He cleaned the fish before cooking.",
    "She fed the cat and the dog.",
    "I helped my brother with his homework.",
    "They visited an art gallery in Paris.",
    "He dropped his pen during the exam.",
    "She kept a journal during her trip.",
    "I brushed the dust off the shelf.",
    "They wore costumes to the party.",
    "We collected shells on the beach.",
    "He closed the curtains before sleeping.",
    "I entered the competition last year.",
    "They walked around the entire lake.",
    "We cleaned the windows with vinegar.",
    "He watched birds in the park.",
    "I made a sandwich with ham and cheese.",
    "We moved the furniture to clean better.",
    "He sorted the mail into piles.",
    "She washed the car on Sunday.",
    "They put the groceries away quickly.",
    "We opened all the windows to let air in.",
    "He counted the money before paying.",
    "She took a deep breath and started.",
    "We cut the vegetables for the salad.",
    "He lost his way in the dark.",
    "She turned off her phone during class.",
    "I invited everyone to the barbecue.",
    "I peeled the potatoes for dinner.",
    "They sorted the papers by date.",
    "We walked in silence for a while.",
    "He changed his mind at the last minute.",
    "They waited outside in the cold.",
    "He trimmed the bushes in the garden.",
    "She combed her hair in front of the mirror.",
    "I opened the box and looked inside.",
    "They explored the cave with flashlights.",
    "He turned the page and kept reading.",
    "She smiled when she saw the flowers.",
    "I handed him the envelope quietly.",
    "They loaded the truck with supplies.",
    "We took a photo near the fountain.",
    "She filled the bathtub with bubbles.",
    "We admired the view from the top.",
    "He sorted the books by color.",
    "She told a joke that made us laugh.",
    "I turned around and saw nothing.",
    "They bought tickets for the concert.",
    "We tried a new restaurant downtown.",
    "She hung her coat by the door",
    "They waited in line for popcorn",
    "We built a sandcastle by the shore",
    "He waved at me from across the street",
    "I have been working on my novel for three months",
    "Has John been studying for his exams all week?",
    "She has not been feeling well since last night",
    "Had Emma been practicing yoga before the class started?",
    "We had not seen such a great performance until yesterday",
    "If I had more time, I would learn to paint",
    "Would Sarah travel abroad if she won the lottery?",
    "He would not help us even if we begged him",
    "I wish I could speak French fluently",
    "Does Lisa wish she had taken that job offer?",
    "That noise must be the construction work nearby",
    "She cannot have left her phone at the office again",
    "Might they be planning a surprise party?",
    "The house is cleaned every week by a professional",
    "Was the book written by a famous author?",
    "The new park will be opened next summer",
    "Did Anna say why she was late for the meeting?",
    "Jack asked if I could meet him at the café",
    "I turned down the invitation because I was tired",
    "Have they run out of tickets for the concert?",
    "She picked up some new phrases during her trip",
    "He is fond of playing soccer with his friends",
    "Are you worried about the upcoming presentation?",
    "They are tired of waiting for the delayed flight",
    "Although it was cold, John went for a run",
    "They studied hard; therefore, they passed the exam",
    "The teacher, an experienced educator, inspired us all",
    "I saw a dog chasing its tail in the park",
    "Is there a reason why the event was canceled?",
    "Not only did she win the race, but she also broke a record",
    "Rarely have I seen such a well-organized event",
    "They have been renovating their apartment for weeks",
    "Has Mike been training for the marathon all month?",
    "We have not been visiting our relatives lately",
    "If I were you, I would apologize immediately",
    "Would Emma stay longer if she had more vacation days?",
    "I wish I had not forgotten my lines during the play",
    "He must have left early to catch the train",
    "The room was decorated by the team yesterday",
    "Will the report be submitted by tomorrow?",
    "Did Tom ask where the meeting was held?",
    "They looked after my cat while I was away",
    "She is good at coming up with creative ideas",
    "Never have we experienced such a warm welcome",
    "He has been saving money for a new car",
    "Had they been traveling for hours before the storm hit?",
    "I have not been sleeping well this week",
    "If we had a bigger house, we would host more parties",
    "Would you move to the city if you got a better job?",
    "Anna would not agree even if we explained everything",
    "I wish I could visit my grandparents more often",
    "Does he wish he had chosen a different path?",
    "That smell must be from the bakery down the street",
    "Might they be discussing the new project now?",
    "The windows are cleaned every month by a service",
    "Was the movie directed by a new filmmaker?",
    "The new bridge will be completed by next year",
    "He told us that he had been planning a trip",
    "Did Sarah mention when the party starts?",
    "Emma asked if I was free this weekend",
    "I gave up sweets to improve my health",
    "Have they sorted out the issues with the plan?",
    "He came across an old diary in the attic",
    "She is keen on learning about history",
    "Are you nervous about the job interview?",
    "They are fed up with the constant noise outside",
    "However, he finished the task despite the distractions",
    "Although it was late, she kept working",
    "They practiced daily; therefore, they improved quickly",
    "The chef, a talented artist, created a masterpiece",
    "I found a book about space in the library",
    "Is there a way to make this process easier?",
    "Seldom have we met someone so kind",
    "She has been writing a blog for six months",
    "Had John been working late before the deadline?",
    "They have not been exercising regularly this month",
    "Would Lisa help us if we asked her politely?",
    "He must have taken the wrong bus this morning",
    "Will the event be held indoors if it rains?",
    "They set off for the airport early today",
    "I have been practicing the piano for a year",
    "He has not been paying attention in class lately",
    "They had left the house before the rain started",
    "Had Sarah been waiting long before the bus came?",
    "I had not realized how difficult the task was",
    "If we knew the answer, we would tell you",
    "Would you stay if the weather got better?",
    "He would not admit his mistake even if we asked",
    "They might be planning a vacation now",
    "Must he be working on the report alone?",
    "The room was painted by a professional last week",
    "Is the building being renovated this month?",
    "The new rules will be announced next week",
    "Did Lisa say what time the meeting starts?",
    "Jack asked if I could lend him a book",
    "I passed up the chance to join the club",
    "Have they worked out the schedule yet?",
    "She ran into an old classmate at the store",
    "He is interested in learning to code",
    "Are you excited about the new project?",
    "However, she continued despite the challenges",
    "Although he was tired, he finished the task",
    "She studied well; therefore, she got a high score",
    "The artist, a creative genius, inspired the crowd",
    "I saw a movie about adventure last weekend",
    "Is there a problem with the new software?",
    "They have been planning their wedding for months",
    "Has Mark been training for the race all year?",
    "We have not been going to the park recently",
    "Would Anna call if she needed advice?",
    "The letter was sent to the wrong address",
    "Will the concert be canceled if it snows?",
    "Did Tom mention why he was late?",
    "They looked into the problem and found a solution",
    "Has Emma been reading that book for long?",
    "He has not been visiting his friends often",
    "Had John been traveling before the meeting?",
    "I had not expected such a warm reception",
    "If we had more time, we would visit the museum",
    "Would you move abroad if you got a job offer?",
    "Sarah would not agree even if we explained",
    "I wish I could play the violin better",
    "If only Mike had listened to the advice",
    "That sound must be the neighbors upstairs",
    "She cannot have forgotten the appointment",
    "Might they be discussing the budget now?",
    "The windows are washed every two weeks",
    "The new school will be built by next year",
    "He told us that he had been studying abroad",
    "Did Anna ask where the keys were?",
    "I gave in to their request to change plans",
    "Have they figured out the new system?",
    "He came up with a great idea yesterday",
    "She is fond of reading mystery novels",
    "Are you afraid of failing the test?",
    "However, he kept trying despite the setbacks",
    "The manager, an inspiring leader, gave a speech",
    "I found a wallet on the bus yesterday",
    "Is there a way to fix this issue quickly?",
    "Seldom have we seen such enthusiasm",
    "She has been jogging every morning for a month",
    "Had Tom been working late before the party?",
    "We have not been shopping for clothes recently",
    "Would Lisa stay if the party was fun?",
    "I wish I had not lost my favorite pen",
    "He must have taken the wrong train",
    "The room was cleaned by the staff yesterday",
    "Will the meeting be rescheduled next week?",
    "They set up the decorations for the event",
    "I have been learning to cook new recipes",
    "Has Sarah been practicing her speech all day?",
    "They had left before the storm started",
    "Had Emma been waiting long before the train arrived?",
    "I had not noticed the error until now",
    "If we knew the truth, we would tell you",
    "Would you help if we asked for support?",
    "John would not admit he was wrong",
    "I wish I could afford a vacation",
    "Does Tom wish he had taken that course?",
    "She cannot have left her bag at home",
    "Must he be working on the weekend?",
    "The house was renovated last month",
    "Is the car being repaired today?",
    "He told me that he had been traveling",
    "Jack asked if I could help with the project",
    "I turned off the phone to focus better",
    "Have they worked out the travel plans?",
    "He is good at fixing broken appliances",
    "They are fed up with the slow service",
    "Although he was busy, he helped us",
    "She practiced daily; therefore, she improved",
    "Rarely have I met someone so dedicated",
    "They have been decorating their house for weeks",
    "Has John been training for the competition?",
    "If I were rich, I would travel the world",
    "Would Emma call if she was in trouble?",
    "I wish I had not missed the concert",
    "He must have forgotten the deadline",
    "The cake was made by my mother yesterday",
    "Will the event be postponed if it rains?",
    "Did Tom ask why the plan changed?",
    "They looked after my dog during my trip",
    "He has not been feeling well this month",
    "I had not seen such a beautiful view before",
    "If we had more space, we would adopt a pet",
    "Lisa would not agree even if we tried harder",
    "I wish I could sing like a professional",
    "Might they be organizing a meeting now?",
    "The office is cleaned every evening",
    "Was the play performed by local actors?",
    "The new building will be finished by June",
    "He told us that he had been feeling tired",
    "Did Emma say where the party was?",
    "Jack asked if I was free tomorrow",
    "Have they sorted out the new schedule?",
    "She came across an old letter in the drawer",
    "However, he continued despite the rain",
    "I found a book about history in the shop",
    "Seldom have I seen such a great performance",
    "She has been learning to dance for months",
    "If I had a boat, I would sail every weekend",
    "Would Lisa help if we needed her?",
    "I wish I had not lost my watch",
    "He must have taken the wrong exit",
    "Has Emma been working on her project all day?",
    "I wish I could afford a new car",
    "The windows are cleaned every Friday",
    "She has been preparing for the exam for weeks",
    "Has Tom been working on his car all weekend?",
    "They have not been attending classes regularly",
    "Had Lisa been practicing her speech before the event?",
    "I had not visited the museum until last month",
    "If I had more money, I would buy a new laptop",
    "Would Emma travel to Paris if she had the chance?",
    "He would not join us even if we invited him",
    "I wish I could run faster in races",
    "Does Mike wish he had studied engineering?",
    "That noise must be from the street festival",
    "She cannot have left her laptop at the café",
    "Might they be planning a team-building event?",
    "The classroom is cleaned every day by the staff",
    "Was the novel written by a young author?",
    "The new theater will be opened next fall",
    "He told me that he had been working all weekend",
    "Did Lisa say why she missed the bus?",
    "Jack asked if I could help with the presentation",
    "I turned down the job because of the schedule",
    "Have they run out of materials for the project?",
    "She picked up some Spanish during her trip",
    "He is fond of playing board games with friends",
    "Are you worried about the project deadline?",
    "They are tired of the same old menu",
    "However, she finished the task despite the rain",
    "Although it was cold, John went hiking",
    "They studied hard; therefore, they passed the test",
    "The professor, a renowned expert, gave a speech",
    "I saw a bird nesting in the tree yesterday",
    "Is there a way to finish this project faster?",
    "Not only did she pass, but she also got an A",
    "Rarely have I seen such a talented performer",
    "They have been decorating the house for the party",
    "Has Emma been practicing her piano all evening?",
    "We have not been going to concerts lately",
    "Would Tom stay if the food was better?",
    "I wish I had not lost my favorite jacket",
    "The cake was baked by my cousin for the wedding",
    "Will the meeting be held online tomorrow?",
    "She said that she had been feeling nervous",
    "Did Mike ask where the keys were?",
    "They looked after my plants during my trip",
    "She is good at solving tricky problems",
    "Never have we seen such a beautiful view",
    "I have been learning to code for six months",
    "He has not been exercising much this month",
    "Had John been waiting long before the train came?",
    "I had not noticed the mistake until yesterday",
    "If we had a bigger car, we would travel more",
    "Would you move if you found a better apartment?",
    "Lisa would not tell us even if she knew the truth",
    "I wish I could play chess better",
    "Does Tom wish he had taken that course?",
    "That smell must be from the kitchen next door",
    "The windows are washed every week by a cleaner",
    "Was the song written by a famous composer?",
    "The new library will be built by next summer",
    "Did Emma mention when the event starts?",
    "Jack asked if I was free this evening",
    "I gave up chocolate to improve my diet",
    "Have they sorted out the travel arrangements?",
    "She came across an old photo in the album",
    "He is keen on learning about technology",
    "Are you nervous about the upcoming test?",
    "They are fed up with the constant delays",
    "However, he finished despite the interruptions",
    "Although it was late, she kept studying",
    "They worked hard; therefore, they got promoted",
    "I found a book about nature in the store",
    "Rarely have I met someone so inspiring",
    "She has been gardening every weekend this year",
    "Had Tom been practicing before the concert?",
    "We have not been visiting our friends lately",
    "If I had a bike, I would cycle to work",
    "Would Lisa help if we asked her nicely?",
    "The room was decorated for the party yesterday",
    "Will the project be finished by next month?",
    "She said that she had been working all weekend",
    "Did Mike explain why he was late again?",
    "They set up the tent for the camping trip",
    "I have been painting my house for two weeks",
    "Has Anna been preparing for her interview?",
    "Would you stay if the hotel was better?",
    "Emma would not agree even if we begged her",
    "I wish I could swim faster",
    "That noise must be the kids playing outside",
    "Was the book published by a small company?",
    "The new bridge will be opened next spring",
    "He told me that he had been feeling stressed",
    "Jack asked if I could lend him my notes",
    "I turned off my phone to avoid distractions",
    "She ran into her old teacher at the mall",
    "He is good at fixing broken computers",
    "Are you excited about the new movie?",
    "They are annoyed with the slow service",
    "However, she continued despite the cold weather",
    "Although he was tired, he finished the report",
    "They practiced daily; therefore, they won",
    "The chef, a creative genius, cooked a great meal",
    "I saw a documentary about history last night",
    "Is there a way to improve this system?",
    "Seldom have I seen such a kind person",
    "They have been planning a trip for months",
    "I wish I had not missed the train yesterday",
    "Jack asked if I was joining the team",
    "I have been studying German for over a year",
    "Has Emma been working on her thesis all month?",
    "They have not been visiting the city center lately",
    "Had Sarah been practicing her lines before the show?",
    "I had not seen such a colorful market until today",
    "If I had more free time, I would learn to cook",
    "Would Tom travel to Italy if he had the money?",
    "She would not join the club even if we asked her",
    "I wish I could speak Italian fluently",
    "Does Mike wish he had chosen a different major?",
    "That sound must be from the construction site",
    "The classroom is cleaned every day by the janitor",
    "Was the book written by an unknown author?",
    "The new bridge will be opened next summer",
    "Did Lisa say why she missed the train?",
    "I turned down the offer because of the long hours",
    "Have they run out of supplies for the workshop?",
    "She picked up some Italian during her trip",
    "He is fond of playing chess with his brother",
    "Are you worried about the upcoming exam?",
    "They are tired of the same old schedule",
    "They studied hard; therefore, they passed",
    "The professor, an expert in history, gave a lecture",
    "I saw a cat sleeping on the windowsill",
    "Is there a way to finish this earlier?",
    "Rarely have I seen such a talented dancer",
    "They have been planning a party for months",
    "Has Emma been practicing her piano all evening?",
    "Would Lisa stay if the event was more fun?",
    "I wish I had not lost my favorite necklace",
    "The room was decorated by the team for the party",
    "Will the building be finished by next month?",
    "They looked after my plants during my vacation",
    "She is good at creating unique artwork",
    "Never have we seen such a beautiful sunset",
    "Has Mike been working on his novel all week?",
    "He has not been attending classes regularly",
    "Had Anna been waiting long before the bus arrived?",
    "I had not noticed the mistake until this morning",
    "If we had a bigger budget, we would expand the event",
    "I wish I could play the drums better",
    "Does she wish she had studied law?",
    "The windows are cleaned every week by a service",
    "Was the song composed by a young musician?",
    "The new park will be opened next spring",
    "He told us that he had been traveling for weeks",
    "Jack asked if I could join the hiking group",
    "Have they sorted out the event schedule?",
    "She came across an old photo in the attic",
    "He is keen on learning about astronomy",
    "They are fed up with the unreliable internet",
    "Although it was cold, she went for a walk",
    "The writer, a talented author, published a novel",
    "I found a painting in the thrift store",
    "Is there a way to simplify this task?",
    "Seldom have I met someone so dedicated",
    "She has been writing short stories for months",
    "I have been learning to knit for weeks",
    "He is good at solving technical problems",
    "However, she continued despite the distractions",
    "Is there a way to fix this error?",
    "Rarely have I seen such a beautiful view",
    "They have been planning a wedding for months",
    "I wish I had not lost my favorite hat",
    "If we had a bigger house, we would invite friends",
    "I wish I could sing better on stage",
    "If only Mike had listened to the instructions",
    "Might they be planning a team meeting?",
    "Jack asked if I was free this weekend",
    "The artist, a creative genius, painted a masterpiece",
    "I found a book about science in the store",
    "They set up the stage for the performance",
    "Had Sarah been waiting long before the train came?",
    "I wish I could afford a new laptop",
    "Was the book published by a local press?",
    "The new rules will be announced next month",
    "He told me that he had been feeling tired",
    "Jack asked if I could join the project",
    "I turned off my phone to focus better",
    "Have they worked out the new plan?",
    "He is fond of collecting vintage records",
    "Although he was tired, he kept working",
    "They studied daily; therefore, they succeeded",
    "I saw a movie about history last weekend.",
    "Is there a way to fix this system?",
    "They have been planning a trip for weeks.",
    "She has been preparing for the exam all week.",
    "I had never tried sushi until last month.",
    "If I had more time, I would learn to play the guitar.",
    "The house was renovated by a local company last year.",
    "He asked if I could meet him at the station.",
    "They have been working on the new project for months.",
    "Seldom have I met someone so inspiring.",
    "Although it was cold, we went for a walk.",
    "The book, a thrilling mystery, kept me up all night.",
    "I wish I hadn’t forgotten to call my friend.",
    "She might have left her phone at the café.",
    "The new library will be opened next spring.",
    "They studied hard; therefore, they passed the test.",
    "Had John been waiting long before the bus arrived?",
    "I haven’t been feeling well since yesterday.",
    "If I were rich, I would travel the world.",
    "He told me that he had been working late.",
    "Never have we seen such a colorful festival.",
    "The windows are cleaned every week by a service.",
    "Would Lisa stay if the party was more fun?",
    "She can’t have finished the report so quickly.",
    "They had left the house before the storm hit.",
    "I found a painting in the antique shop yesterday.",
    "He’s fond of collecting vintage postcards.",
    "Are you worried about the upcoming presentation?",
    "However, she continued studying despite the noise.",
    "The professor, an expert in biology, gave a lecture.",
    "I saw a bird building a nest in the garden.",
    "Is there a way to simplify this process?",
    "They have been planning a vacation for weeks.",
    "She turned down the job offer because of the location.",
    "I have been learning to dance for six months.",
    "He hasn’t been exercising regularly this month.",
    "If we had a bigger budget, we would expand the event.",
    "The room was decorated by the team for the party.",
    "Did Emma mention why she missed the meeting?",
    "I wish I could speak Italian fluently.",
    "Might they be organizing a surprise party?",
    "The new bridge will be completed by next summer.",
    "He came across an old photo in the attic.",
    "She’s good at solving complex puzzles.",
    "They’re fed up with the unreliable internet service.",
    "Although he was tired, he finished the report.",
    "They practiced daily; therefore, they improved quickly.",
    "I found a book about history in the library.",
    "Rarely have I seen such a dedicated team.",
    "She has been writing a novel for over a year.",
    "Had Tom been practicing before the concert?",
    "We haven’t been visiting our relatives lately.",
    "Would you move abroad if you got a job offer?",
    "He must have taken the wrong train this morning.",
    "The cake was baked by my sister for the wedding.",
    "Will the meeting be held online tomorrow?",
    "She said that she had been feeling nervous.",
    "They looked after my dog during my trip.",
    "He’s keen on learning about astronomy.",
    "Are you nervous about the job interview?",
    "However, he continued despite the cold weather.",
    "The artist, a creative genius, painted a mural.",
    "I saw a documentary about nature last night.",
    "Is there a way to fix this system quickly?",
    "They have been organizing a charity event for months.",
    "I turned off my phone to avoid distractions.",
    "I have been jogging every morning for a month.",
    "She hasn’t been sleeping well this week.",
    "If I had a car, I would drive to work.",
    "The office is cleaned every evening by the staff.",
    "Did Mike ask where the keys were?",
    "I wish I hadn’t lost my favorite sunglasses.",
    "Might they be discussing the new budget?",
    "The new museum will be opened next fall.",
    "She ran into her old teacher at the mall.",
    "He’s good at fixing broken electronics.",
    "They’re tired of the same old schedule.",
    "Although it was raining, they went hiking.",
    "The writer, a talented author, published a novel.",
    "I found a wallet on the bus yesterday.",
    "Seldom have I seen such a beautiful sunset.",
    "They have been decorating their house for the party.",
    "She turned down the invitation because she was busy.",
    "I have been learning to cook new recipes for weeks.",
    "He hasn’t been attending classes regularly.",
    "If we had more time, we would explore the city.",
    "The room was painted by a professional last week.",
    "Did Lisa say why she was late?",
    "I wish I could play the piano better.",
    "The windows are washed every two weeks.",
    "He came up with a brilliant idea yesterday.",
    "She’s fond of reading adventure novels.",
    "Are you excited about the new project?",
    "However, she finished the task despite the distractions.",
    "The chef, a skilled professional, cooked a great meal.",
    "I saw a cat sleeping on the windowsill.",
    "Is there a way to finish this project faster?",
    "They have been planning a wedding for months.",
    "I gave up coffee to improve my health.",
    "I have been practicing yoga for three months.",
    "She hasn’t been feeling well since last weekend.",
    "If I were you, I would apologize immediately.",
    "The house was renovated by the team last month.",
    "Did Tom mention when the party starts?",
    "I wish I hadn’t missed the train yesterday.",
    "Might they be planning a team-building event?",
    "The new park will be opened next spring.",
    "She picked up some French during her trip.",
    "He’s good at solving math problems.",
    "They’re fed up with the slow service at the café.",
    "Although he was busy, he helped us.",
    "They studied well; therefore, they got high marks.",
    "I found a book about science in the store.",
    "Never have we seen such a stunning performance.",
    "She has been gardening every weekend this year.",
    "Had Anna been waiting long before the train arrived?",
    "We haven’t been going to concerts lately.",
    "Would Emma call if she needed help?",
    "He must have forgotten to send the email.",
    "The cake was made by my mother for the birthday.",
    "Will the concert be canceled if it snows?",
    "She said that she had been working all day.",
    "They looked after my plants during my vacation.",
    "He’s keen on studying ancient history.",
    "Are you worried about the exam results?",
    "However, he continued despite the rain.",
    "The professor, a renowned expert, gave a speech.",
    "I saw a bird nesting in the tree yesterday.",
    "Is there a way to improve this process?",
    "They have been planning a trip for weeks.",
    "I turned down the offer because of the schedule.",
    "I have been learning to knit for two months.",
    "He hasn’t been visiting his friends often.",
    "If we had a bigger house, we would invite more friends.",
    "The room was decorated by the students for the event.",
    "Did Sarah ask why the meeting was canceled?",
    "I wish I could afford a new laptop.",
    "Might they be organizing a charity event?",
    "The new bridge will be opened next summer.",
    "She came across an old letter in the drawer.",
    "He’s good at designing creative posters.",
    "They’re tired of the constant delays.",
    "Although it was windy, she went cycling.",
    "The writer, a creative storyteller, published a book.",
    "I found a painting in the thrift store.",
    "Rarely have I seen such a kind person.",
    "They have been organizing a festival for months.",
    "I gave in to their request to change plans.",
    "I have been running every morning this month.",
    "She hasn’t been going to the gym lately.",
    "If I had a boat, I would sail every weekend.",
    "The office is cleaned every day by the janitor.",
    "Did Emma say where the party was held?",
    "I wish I hadn’t lost my favorite jacket.",
    "The windows are cleaned every Friday.",
    "He ran into an old classmate at the store.",
    "She’s fond of playing board games with friends.",
    "Are you nervous about the upcoming test?",
    "However, she continued despite the cold weather.",
    "The artist, a talented painter, created a masterpiece.",
    "I saw a documentary about history last weekend.",
    "Is there a way to fix this issue quickly?",
    "They have been planning a party for weeks.",
    "I turned off my phone to focus better.",
    "I have been learning to code for six months.",
    "He hasn’t been feeling well this month.",
    "If we had more money, we would buy a new car.",
    "The room was cleaned by the staff yesterday.",
    "Did Mike explain why he was late?",
    "I wish I could swim faster.",
    "Might they be discussing the new project?",
    "The new theater will be opened next fall.",
    "She picked up some Spanish during her trip.",
    "He’s good at fixing broken appliances.",
    "They’re fed up with the unreliable service.",
    "Although he was tired, he kept working.",
    "They practiced daily; therefore, they won the game.",
    "I found a book about nature in the library.",
    "Seldom have I met someone so dedicated.",
    "She has been writing poetry for months.",
    "Had Tom been working late before the party?",
    "We haven’t been shopping for clothes recently.",
    "Would Lisa help if we asked her nicely?",
    "He must have taken the wrong bus.",
    "The cake was baked by my cousin for the party.",
    "Will the event be postponed if it rains?",
    "She said that she had been studying all night.",
    "They looked after my cat during my trip.",
    "He’s keen on learning about technology.",
    "Are you excited about the new movie?",
    "However, he finished despite the interruptions.",
    "The chef, a creative genius, cooked a great meal.",
    "I saw a cat sleeping in the garden.",
    "Is there a way to simplify this task?",
    "They have been decorating their apartment for weeks.",
    "I gave up chocolate to improve my diet.",
    "I have been practicing the piano for a year.",
    "She hasn’t been visiting her relatives lately.",
    "If I were taller, I would play basketball.",
    "The house was painted by a professional last week.",
    "Did Anna ask where the keys were?",
    "I wish I hadn’t missed the concert.",
    "Might they be planning a new business venture?",
    "The new stadium will be opened next year.",
    "She came across an old diary in the attic.",
    "He’s good at solving technical problems.",
    "They’re tired of the same old menu.",
    "Although it was late, she kept studying.",
    "The writer, a talented author, gave a talk.",
    "I found a wallet in the park yesterday.",
    "Never have we seen such a beautiful view.",
    "They have been planning a hiking trip for months.",
    "I turned down the job because of the long hours.",
    "I have been learning to sew for three months.",
    "He hasn’t been attending meetings regularly.",
    "If we had a bigger budget, we would host a party.",
    "The room was decorated by the team yesterday.",
    "Did Lisa say why she missed the train?",
    "I wish I could play the drums better.",
    "The windows are cleaned every week by a company.",
    "He ran into his old boss at the café.",
    "She’s fond of collecting rare books.",
    "Are you worried about the project deadline?",
    "However, she continued despite the rain.",
    "The professor, an expert in history, published a book.",
    "I saw a bird flying over the lake.",
    "Is there a way to finish this earlier?",
    "They have been organizing a conference for weeks.",
    "I gave up sweets to feel healthier.",
    "I have been jogging every evening for a month.",
    "She hasn’t been going to the library recently.",
    "If I had a dog, I would walk it every day.",
    "The office is cleaned every evening by the staff.",
    "Did Tom ask why the plan changed?",
    "I wish I hadn’t lost my favorite necklace.",
    "Might they be planning a team event?",
    "The new library will be opened next summer.",
    "She picked up some Italian during her vacation.",
    "He’s good at creating unique artwork.",
    "They’re fed up with the constant noise.",
    "Although he was busy, he finished the task.",
    "They studied hard; therefore, they got promoted.",
    "I found a book about animals in the store.",
    "Rarely have I seen such a talented performer.",
    "She has been learning to bake for months.",
    "Had Emma been practicing before the event?",
    "We haven’t been going to the cinema lately.",
    "Would you stay if the hotel was better?",
    "He must have forgotten the deadline.",
    "The cake was made by my aunt for the celebration.",
    "Will the meeting be rescheduled next week?",
    "She said that she had been working all weekend.",
    "They looked after my garden during my absence.",
    "He’s keen on studying marine biology.",
    "Are you nervous about the presentation?",
    "However, he continued despite the challenges.",
    "The artist, a creative genius, painted a portrait.",
    "I saw a documentary about space last night.",
    "Is there a way to improve this system?",
    "They have been planning a charity run for months.",
    "I turned off my phone to study better.",
    "I have been learning to play chess for six months.",
    "She hasn’t been feeling well this week.",
    "If we had more space, we would adopt a pet.",
    "The room was cleaned by the team yesterday.",
    "Did Mike ask where the meeting was held?",
    "I wish I hadn’t lost my favorite hat.",
    "Might they be organizing a community event?",
    "The new bridge will be opened next spring.",
    "She came across an old journal in the closet.",
    "He’s good at solving tricky problems.",
    "They’re tired of the unreliable schedule.",
    "Although it was snowing, they went skiing.",
    "The writer, a talented storyteller, wrote a novel.",
    "I found a painting in the antique shop.",
    "Seldom have I met someone so creative.",
    "They have been decorating their house for weeks.",
    "I gave in to their request to reschedule.",
    "I have been running every morning for three months.",
    "He hasn’t been visiting his family lately.",
    "If I were you, I would take the opportunity.",
    "The house was renovated by a company last year.",
    "Did Emma say why she was late?",
    "I wish I could afford a new phone.",
    "The windows are cleaned every month by a service.",
    "He ran into an old friend at the bookstore.",
    "She’s fond of reading mystery novels.",
    "Are you excited about the upcoming trip?",
    "However, she finished despite the interruptions.",
    "The chef, a skilled artist, created a dessert.",
    "I saw a cat chasing a bird in the garden.",
    "Is there a way to fix this problem quickly?",
    "They have been planning a family reunion for months.",
    "I turned down the offer because of the location.",
    "I have been learning to draw for two months.",
    "She hasn’t been going to the park lately.",
    "If we had a bigger car, we would travel more.",
    "The room was painted by the staff last week.",
    "Did Lisa mention why she canceled the meeting?",
    "I wish I hadn’t missed the deadline.",
    "Might they be discussing the new plan?",
    "The new museum will be opened next spring.",
    "She picked up some German during her trip.",
    "He’s good at designing creative logos.",
    "They’re fed up with the slow internet.",
    "Although he was tired, he helped his friend.",
    "They practiced daily; therefore, they succeeded.",
    "I found a book about technology in the shop.",
    "Never have I seen such a talented musician.",
    "She has been writing a blog for over a year.",
    "Had Tom been waiting long before the train arrived?",
    "We haven’t been visiting the museum lately.",
    "Would Emma stay if the event was more fun?",
    "He must have taken the wrong exit.",
    "The cake was baked by my grandmother for the party.",
    "Will the event be held indoors if it rains?",
    "She said that she had been feeling tired.",
    "They looked after my house during my vacation.",
    "He’s keen on learning about photography.",
    "Are you worried about the upcoming deadline?",
    "However, he continued despite the distractions.",
    "The professor, an expert in physics, gave a lecture.",
    "I saw a bird building a nest in the tree.",
    "Is there a way to finish this task faster?",
    "They have been organizing a fundraiser for weeks.",
    "I gave up soda to improve my health.",
    "I have been learning to play the violin for six months.",
    "She hasn’t been attending classes regularly.",
    "If I had a bike, I would cycle to school.",
    "The office is cleaned every day by the janitor.",
    "Did Anna ask why the event was postponed?",
    "I wish I hadn’t lost my favorite scarf.",
    "Might they be planning a new project?",
    "The new park will be opened next summer.",
    "She came across an old photo in the album.",
    "He’s good at creating unique designs.",
    "They’re tired of the constant traffic.",
    "Although it was cold, she went for a run.",
    "The writer, a creative genius, published a book.",
    "I found a wallet in the café yesterday.",
    "Rarely have I seen such a beautiful view.",
    "They have been planning a trip for months.",
    "I turned down the job because of the salary.",
    "I have been learning to bake for three months.",
    "He hasn’t been going to the gym lately.",
    "If we had more time, we would visit the beach.",
    "The room was decorated by the team for the wedding.",
    "Did Sarah say why she missed the bus?",
    "I wish I could play the guitar better.",
    "The windows are cleaned every week by a cleaner.",
    "He ran into his old teacher at the supermarket.",
    "She’s fond of collecting vintage jewelry.",
    "Are you nervous about the upcoming exam?",
    "However, she continued despite the challenges.",
    "The chef, a talented professional, cooked a feast.",
    "I saw a dog chasing its tail in the park.",
    "Is there a way to simplify this project?",
    "They have been organizing a concert for months.",
    "I gave up sugar to feel healthier.",
    "I have been practicing meditation for two months.",
    "She hasn’t been visiting her friends lately.",
    "If I were rich, I would buy a beach house.",
    "The house was painted by a team last month.",
    "Did Tom ask where the meeting was?",
    "I wish I hadn’t missed the opportunity.",
    "Might they be planning a team outing?",
    "The new bridge will be opened next fall.",
    "She picked up some Portuguese during her trip.",
    "He’s good at solving logical puzzles.",
    "They’re fed up with the unreliable buses.",
    "Although he was busy, he attended the meeting.",
    "They studied hard; therefore, they passed the exam.",
    "I found a book about art in the bookstore.",
    "Seldom have I met someone so talented.",
    "She has been learning to sing for six months.",
    "Had Emma been working late before the deadline?",
    "We haven’t been going to the theater lately.",
    "Would Lisa call if she was in trouble?",
    "He must have left his keys at the office.",
    "The cake was made by my brother for the party.",
    "Will the meeting be canceled if it snows?",
    "She said that she had been studying all day.",
    "They looked after my plants during my trip.",
    "He’s keen on learning about architecture.",
    "Are you excited about the new book?",
    "However, he finished despite the noise.",
    "The artist, a skilled painter, created a portrait.",
    "I saw a cat sleeping on the roof.",
    "Is there a way to fix this error quickly?",
    "They have been planning a family trip for weeks.",
    "He has been working on his car all weekend.",
    "I had never visited a museum until last summer.",
    "If I had more money, I would buy a new phone.",
    "The room was cleaned by the hotel staff yesterday.",
    "She asked if I could join her for dinner.",
    "They have been planning a road trip for weeks.",
    "Never have I seen such a lively concert.",
    "Although it was snowing, we went for a hike.",
    "The book, a historical novel, was fascinating.",
    "I wish I hadn’t lost my favorite gloves.",
    "They might have left their bags at the airport.",
    "The new school will be opened next fall.",
    "They worked hard; therefore, they got promoted.",
    "Had Lisa been studying before the exam started?",
    "I haven’t been sleeping well lately.",
    "If I were famous, I would help charities.",
    "He told me that he had been traveling abroad.",
    "Seldom have we met someone so generous.",
    "The windows are washed every month by a cleaner.",
    "Would Tom stay if the weather was better?",
    "She can’t have completed the project so fast.",
    "We had left the party before the fight started.",
    "I found a coin on the street yesterday.",
    "He’s fond of playing chess with his grandfather.",
    "Are you nervous about the upcoming interview?",
    "However, she continued despite the challenges.",
    "The teacher, an inspiring figure, motivated the class.",
    "I saw a dog running in the park this morning.",
    "Is there a way to speed up this process?",
    "They have been decorating the office for the event.",
    "I turned down the offer because of the long hours.",
    "I have been learning to play the flute for months.",
    "She hasn’t been feeling well this week.",
    "If we had a bigger apartment, we would get a pet.",
    "The house was painted by a professional last month.",
    "Did Emma ask why the event was canceled?",
    "I wish I could speak Japanese fluently.",
    "Might they be planning a team outing?",
    "The new bridge will be completed next spring.",
    "He came across an old watch in the attic.",
    "She’s good at writing creative stories.",
    "They’re fed up with the noisy neighbors.",
    "Although he was busy, he attended the meeting.",
    "They practiced daily; therefore, they won the match.",
    "I found a book about art in the bookstore.",
    "Rarely have I seen such a talented artist.",
    "She has been jogging every evening for a month.",
    "Had John been working late before the deadline?",
    "We haven’t been going to the beach lately.",
    "Would you move to the countryside if you could?",
    "He must have forgotten to lock the door.",
    "The cake was baked by my friend for the party.",
    "Will the concert be held indoors if it rains?",
    "She said that she had been studying all day.",
    "They looked after my fish during my vacation.",
    "He’s keen on learning about world cultures.",
    "Are you excited about the new restaurant?",
    "However, he finished the task despite the noise.",
    "The artist, a skilled painter, created a portrait.",
    "I saw a cat climbing a tree yesterday.",
    "Is there a way to fix this problem quickly?",
    "They have been organizing a fundraiser for weeks.",
    "I gave up soda to improve my health.",
    "I have been practicing yoga for two months.",
    "He hasn’t been visiting his parents often.",
    "If I had a bike, I would cycle to work.",
    "The office is cleaned every evening by the staff.",
    "Did Sarah ask where the meeting was held?",
    "I wish I hadn’t missed the movie last night.",
    "Might they be discussing the new schedule?",
    "The new park will be opened next summer.",
    "She ran into her old classmate at the café.",
    "He’s good at fixing broken furniture.",
    "They’re tired of the slow internet connection.",
    "Although it was cold, she went for a run.",
    "The writer, a talented author, published a novel.",
    "I found a wallet in the subway yesterday.",
    "Seldom have I seen such a beautiful view.",
    "They have been planning a wedding for months.",
    "I turned down the job because of the commute.",
    "I have been learning to cook Italian dishes for weeks.",
    "She hasn’t been going to the gym recently.",
    "If we had more time, we would visit the museum.",
    "The room was decorated by the team for the event.",
    "Did Mike say why he was late?",
    "I wish I could play the violin better.",
    "The windows are cleaned every week by a service.",
    "He came up with a creative solution yesterday.",
    "She’s fond of reading science fiction novels.",
    "Are you worried about the project deadline?",
    "However, she continued despite the rain.",
    "The professor, an expert in literature, gave a talk.",
    "I saw a bird flying over the river.",
    "Is there a way to simplify this task?",
    "They have been organizing a charity event for months.",
    "I gave up sweets to feel healthier.",
    "I have been running every morning for three months.",
    "He hasn’t been attending classes regularly.",
    "If I were you, I would take the opportunity.",
    "The house was renovated by a local team last year.",
    "Did Anna ask why the plan changed?",
    "I wish I hadn’t lost my favorite scarf.",
    "Might they be planning a surprise party?",
    "The new library will be opened next spring.",
    "She picked up some Spanish during her trip.",
    "He’s good at designing unique logos.",
    "They’re fed up with the unreliable buses.",
    "Although he was tired, he helped his friend.",
    "They studied hard; therefore, they passed the exam.",
    "I found a book about technology in the shop.",
    "Never have I seen such a talented musician.",
    "She has been learning to dance for six months.",
    "Had Tom been practicing before the performance?",
    "We haven’t been visiting the city center lately.",
    "Would Emma stay if the event was more fun?",
    "He must have left his keys at the office.",
    "The cake was made by my sister for the birthday.",
    "Will the meeting be canceled if it snows?",
    "She said that she had been working all weekend.",
    "They looked after my plants during my trip.",
    "He’s keen on studying archaeology.",
    "Are you nervous about the upcoming exam?",
    "However, he continued despite the distractions.",
    "The artist, a creative genius, painted a mural.",
    "I saw a dog chasing a cat in the yard.",
    "Is there a way to finish this project faster?",
    "They have been planning a family reunion for weeks.",
    "I turned down the offer because of the salary.",
    "I have been learning to play chess for months.",
    "She hasn’t been feeling well lately.",
    "If we had a bigger house, we would host parties.",
    "The room was painted by the staff last week.",
    "Did Lisa mention why she missed the bus?",
    "I wish I could afford a new laptop.",
    "Might they be organizing a team meeting?",
    "The new stadium will be opened next fall.",
    "She came across an old letter in the closet.",
    "He’s good at solving technical issues.",
    "They’re tired of the constant traffic.",
    "Although it was late, she kept studying.",
    "The writer, a skilled storyteller, wrote a book.",
    "I found a painting in the antique shop.",
    "Rarely have I met someone so kind.",
    "They have been decorating their apartment for weeks.",
    "I gave in to their request to reschedule.",
    "I have been practicing meditation for two months.",
    "He hasn’t been going to the library recently.",
    "If I were rich, I would buy a beach house.",
    "The office is cleaned every day by the janitor.",
    "Did Emma ask why the event was postponed?",
    "I wish I hadn’t missed the concert.",
    "The windows are cleaned every Friday.",
    "He ran into his old boss at the bookstore.",
    "She’s fond of collecting vintage clothes.",
    "Are you excited about the new project?",
    "However, she finished despite the cold weather.",
    "The chef, a talented professional, cooked a feast.",
    "I saw a cat sleeping on the porch.",
    "Is there a way to improve this system?",
    "They have been organizing a concert for months.",
    "I gave up coffee to improve my sleep.",
    "I have been learning to draw for three months.",
    "She hasn’t been visiting her friends lately.",
    "If I had a dog, I would walk it every day.",
    "The house was renovated by a company last month.",
    "Did Tom ask where the keys were?",
    "I wish I hadn’t lost my favorite hat.",
    "Might they be planning a community event?",
    "The new park will be opened next spring.",
    "She picked up some French during her vacation.",
    "He’s good at creating unique designs.",
    "They’re fed up with the slow service.",
    "Although he was busy, he finished the task.",
    "They practiced daily; therefore, they succeeded.",
    "I found a book about animals in the store.",
    "Seldom have I seen such a creative team.",
    "She has been writing a blog for over a year.",
    "Had Anna been waiting long before the train arrived?",
    "We haven’t been going to the theater lately.",
    "Would you stay if the hotel was better?",
    "He must have taken the wrong exit.",
    "The cake was baked by my mother for the wedding.",
    "Will the event be held online tomorrow?",
    "She said that she had been feeling tired.",
    "They looked after my cat during my absence.",
    "He’s keen on learning about photography.",
    "Are you worried about the upcoming deadline?",
    "However, he continued despite the rain.",
    "The artist, a skilled painter, created a masterpiece.",
    "I saw a bird nesting in the garden.",
    "Is there a way to fix this error quickly?",
    "They have been planning a charity run for months.",
    "I turned down the job because of the location.",
    "I have been learning to sew for two months.",
    "She hasn’t been attending meetings regularly.",
    "If we had more space, we would adopt a pet.",
    "The room was decorated by the students yesterday.",
    "Did Sarah say why she missed the train?",
    "I wish I could play the guitar better.",
    "The windows are cleaned every week by a company.",
    "He came across an old diary in the attic.",
    "She’s fond of reading mystery books.",
    "Are you nervous about the presentation?",
    "However, she continued despite the distractions.",
    "The professor, an expert in physics, gave a lecture.",
    "I saw a dog playing in the park.",
    "Is there a way to simplify this project?",
    "They have been organizing a festival for weeks.",
    "I gave up sugar to feel healthier.",
    "I have been practicing the piano for six months.",
    "He hasn’t been going to the gym lately.",
    "If I were taller, I would play volleyball.",
    "The office is cleaned every evening by the staff.",
    "Did Mike ask why the meeting was canceled?",
    "I wish I hadn’t missed the deadline.",
    "Might they be discussing the new plan?",
    "The new museum will be opened next summer.",
    "She picked up some Italian during her trip.",
    "He’s good at solving logical puzzles.",
    "They’re tired of the unreliable schedule.",
    "Although it was windy, he went cycling.",
    "The writer, a talented author, published a book.",
    "I found a wallet in the café yesterday.",
    "Never have I seen such a stunning sunset.",
    "They have been planning a family trip for months.",
    "I turned down the offer because of the hours.",
    "I have been learning to bake for three months.",
    "She hasn’t been visiting her family lately.",
    "If we had a bigger car, we would travel more.",
    "The room was painted by the team last week.",
    "Did Lisa ask why the event was delayed?",
    "I wish I could afford a new car.",
    "Might they be organizing a team event?",
    "The new bridge will be opened next fall.",
    "She came across an old photo in the album.",
    "He’s good at creating unique artwork.",
    "They’re fed up with the constant noise.",
    "Although he was tired, he kept studying.",
    "They studied hard; therefore, they got high marks.",
    "I found a book about science in the library.",
    "Rarely have I seen such a dedicated person.",
    "She has been learning to sing for months.",
    "Had Emma been practicing before the show?",
    "We haven’t been going to the cinema lately.",
    "Would Tom call if he needed advice?",
    "He must have forgotten to send the email.",
    "The cake was made by my aunt for the celebration.",
    "Will the meeting be rescheduled next week?",
    "She said that she had been working all day.",
    "They looked after my garden during my trip.",
    "He’s keen on studying marine biology.",
    "Are you excited about the new book?",
    "However, he finished despite the cold weather.",
    "The artist, a creative genius, painted a portrait.",
    "I saw a cat sleeping in the sun.",
    "Is there a way to finish this task faster?",
    "They have been organizing a conference for months.",
    "I gave up chocolate to improve my diet.",
    "I have been running every evening for a month.",
    "She hasn’t been attending classes lately.",
    "If I were you, I would accept the offer.",
    "The house was renovated by a team last year.",
    "Did Anna ask where the meeting was?",
    "I wish I hadn’t lost my favorite necklace.",
    "Might they be planning a new project?",
    "The new park will be opened next spring.",
    "She picked up some German during her trip.",
    "He’s good at designing creative posters.",
    "They’re tired of the slow traffic.",
    "Although it was late, he kept working.",
    "The writer, a skilled storyteller, gave a talk.",
    "I found a painting in the thrift store.",
    "Seldom have I met someone so talented.",
    "They have been decorating their house for weeks.",
    "I turned down the job because of the schedule.",
    "I have been learning to play the drums for months.",
    "He hasn’t been visiting his friends lately.",
    "If we had more time, we would go hiking.",
    "The room was decorated by the team for the party.",
    "Did Sarah ask why the plan was changed?",
    "I wish I could play the piano better.",
    "The windows are cleaned every week by a cleaner.",
    "He ran into his old teacher at the mall.",
    "She’s fond of collecting rare coins.",
    "Are you worried about the upcoming test?",
    "However, she continued despite the noise.",
    "The professor, an expert in history, published a book.",
    "I saw a bird flying over the lake.",
    "Is there a way to fix this system?",
    "They have been planning a charity event for months.",
    "I gave up tea to improve my health.",
    "I have been practicing meditation for three months.",
    "She hasn’t been going to the park lately.",
    "If I had a boat, I would sail every weekend.",
    "The office is cleaned every day by the staff.",
    "Did Tom ask why the event was canceled?",
    "I wish I hadn’t missed the train.",
    "Might they be organizing a community project?",
    "The new library will be opened next fall.",
    "She came across an old journal in the attic.",
    "He’s good at solving math problems.",
    "They’re fed up with the unreliable internet.",
    "Although he was busy, he helped his neighbor.",
    "They practiced daily; therefore, they won.",
    "I found a book about nature in the bookstore.",
    "Never have I seen such a beautiful festival.",
    "She has been learning to draw for six months.",
    "Had Lisa been working late before the party?",
    "We haven’t been visiting the museum lately.",
    "Would Emma stay if the party was better?",
    "He must have left his phone at home.",
    "The cake was baked by my brother for the event.",
    "Will the concert be postponed if it rains?",
    "She said that she had been studying all night.",
    "They looked after my dog during my vacation.",
    "He’s keen on learning about astronomy.",
    "Are you nervous about the upcoming deadline?",
    "However, he continued despite the challenges.",
    "The artist, a talented painter, created a mural.",
    "I saw a cat chasing a bird in the park.",
    "Is there a way to simplify this process?",
    "They have been organizing a wedding for months."
  ]
};
