export const sortSentenceData = {
  "s": [
    "He has been working here for three years",
    "Neither Jack nor Emma wanted to leave early",
    "If it rains tomorrow, we will cancel the trip",
    "This is the book that I told you about",
    "I had never seen such a beautiful sunset before",
    "We have been studying English for two years",
    "The man who lives next door is a doctor",
    "They were watching TV when the lights went out",
    "She has just finished her homework",
    "I think it will snow tomorrow",
    "You should try to get more sleep",
    "She might come to the party later",
    "Neither of the answers was correct",
    "You do not need to bring anything",
    "We were walking when it started to rain",
    "It is important to take a break sometimes",
    "I am going to visit my grandparents this weekend",
    "The cake was made by my mom",
    "If I were you, I would apologize",
    "I have not seen him since last week",
    "You must wear a helmet when riding a bike",
    "Either you or your brother has to go",
    "There is too much noise in this room",
    "It had been raining all morning",
    "This is the place where we met",
    "She asked if I liked chocolate",
    "You look tired. You should rest.",
    "I will help you as soon as I finish this",
    "We have been waiting for over an hour",
    "He is the one who broke the window",
    "I do not know what she wants",
    "Not only did he win the race, but he also broke the record",
    "There is not enough time to explain everything",
    "She speaks Spanish as well as English",
    "I will call you when I arrive",
    "You ought to see a doctor",
    "The house was built in 1920",
    "She used to live in a small village",
    "They are planning to visit Italy next summer",
    "If you work harder, you will achieve your goals",
    "My cousin has just returned from Japan",
    "Unless we hurry, we will miss the train",
    "He has not decided what to do next",
    "They were arguing about something unimportant",
    "He might be working late tonight",
    "We have never been to that restaurant before",
    "Could you explain this again, please?",
    "She did not remember locking the door",
    "We were having dinner when it started snowing",
    "I do not know if she will agree",
    "You should not talk during the movie",
    "She always brings snacks to the meeting",
    "We need to discuss the new proposal",
    "He was injured while playing football",
    "I wonder how they solved the problem",
    "Have you heard anything from him recently?",
    "She speaks more clearly than her sister",
    "This book is more interesting than the last one",
    "He promised he would be careful",
    "I was not sure whether to laugh or cry",
    "She told me not to be late",
    "They might have forgotten the appointment",
    "Why do not we take a break now?",
    "This song reminds me of my childhood",
    "Let me know if anything changes",
    "He managed to fix the broken chair",
    "Would you like something to drink?",
    "I will call you when I get home",
    "He has been learning French for a year",
    "It is hard to understand his handwriting",
    "She refused to answer the question",
    "What would you do in my place?",
    "I had trouble finding the place",
    "Do you remember meeting her before?",
    "He got used to living alone",
    "The teacher explained it very well",
    "Is there anything I can help with?",
    "I saw a cat chasing a bird in the park.",
    "Is there a way to simplify this process?",
    "They have been organizing a wedding for months."
  ]
};
