export const sortSentenceData = {
  "s": [
    "My brother usually takes the bus to school",
    "We visited a small museum last Saturday",
    "The children are learning English together",
    "I have never tried Japanese food",
    "I have just finished my homework",
    "She has already visited Paris",
    "They have never tried sushi",
    "He has not seen that movie yet",
    "Have you ever been to London?",
    "We have just eaten lunch",
    "I have not finished my project yet",
    "Has she already called you?",
    "They have never gone skiing",
    "Have we ever met before?",
    "She has just bought a new dress",
    "I have not been to the beach this year",
    "Have you already finished your dinner?",
    "He has never played tennis",
    "They have not seen the new museum yet",
    "Have you ever tried painting?",
    "I have already booked the tickets",
    "She has not learned Spanish yet",
    "Have they ever visited Rome?",
    "We have just arrived home",
    "They were watching a movie last night",
    "She was not studying when I called",
    "Were you playing football yesterday?",
    "He was reading a book in the park",
    "We were not working late last night",
    "Was she cooking dinner earlier?",
    "I was walking to school when it rained",
    "They were not listening to music",
    "Were you waiting for the bus?",
    "He was painting the house all day",
    "She was writing a letter yesterday",
    "I was not watching TV last night",
    "Were they running in the park?",
    "He was cleaning the car this morning",
    "We were not talking during the class",
    "Was she reading a novel?",
    "They were playing games all evening",
    "I was not sleeping when you called",
    "Were you working on your project?",
    "She was singing in the shower",
    "If it rains, we will stay home",
    "If you do not study, you will not pass",
    "Will she come if we invite her?",
    "If we leave now, we will catch the bus",
    "He will not help if you do not ask",
    "Will they win if they practice?",
    "If I save money, I will buy a phone",
    "She will not call if she is busy",
    "Will you visit if you have time?",
    "If we hurry, we will arrive early",
    "If he studies, he will pass the exam",
    "If you do not call, I will not know",
    "Will we go if it is sunny?",
    "If she works hard, she will get promoted",
    "They will not come if it is late",
    "Will you help if I ask?",
    "If I finish early, I will meet you",
    "He will not go if it is cold",
    "Will she stay if we need her?",
    "If we do not leave now, we will be late",
    "You should eat more fruit",
    "We must not be late for school",
    "Do I have to finish this today?",
    "She should call her friend",
    "He does not have to work tomorrow",
    "Must we sign the form now?",
    "You should try this new game",
    "They must not use phones in class",
    "Does she have to stay late?",
    "I should study for the test",
    "He should visit his grandparents",
    "We do not have to wear uniforms",
    "Should I call her now?",
    "They must clean their room",
    "She does not have to come early",
    "Must you leave so soon?",
    "You should read this book",
    "He must not talk during the movie",
    "Do we have to write a report?",
    "She should rest after work",
    "Life is easier now with smartphones",
    "People do not write letters anymore",
    "Is your city bigger now than before?",
    "We use computers more than we did",
    "She does not walk to school now",
    "Was life simpler in the past?",
    "Kids play outside less than before",
    "I do not send postcards anymore",
    "Is shopping easier now than before?",
    "We travel more now than in the past",
    "Houses are bigger now than before",
    "They do not play board games anymore",
    "Is your school better now than it was?",
    "I use my phone more than I did",
    "He does not ride a bike now",
    "Was food cheaper in the past?",
    "We do not visit friends as often now",
    "She does not read newspapers anymore",
    "Is life busier now than before?",
    "They travel less now than they did",
    "The girl who sings is my sister",
    "The book that I read was not good",
    "Which movie do you like?",
    "The dog which lives here is friendly",
    "The man who called was kind",
    "Is this the car that you bought?",
    "The teacher who helped me was nice",
    "The phone that I want is expensive",
    "Who is the boy that plays soccer?",
    "The house which we saw was old",
    "The woman who teaches us is strict",
    "The game that we played was not fun",
    "Which song do you love?",
    "The cat which sleeps here is cute",
    "The friend who visited me was funny",
    "Is this the book that you read?",
    "The doctor who treated me was kind",
    "The laptop that I bought is fast",
    "Who is the girl that dances well?",
    "The park which we visited was big",
    "You are tired, aren't you?",
    "She does not live here, does she?",
    "He can drive, can't he?",
    "We are late, aren't we?",
    "They do not know him, do they?",
    "You have finished, haven't you?",
    "She likes tea, doesn't she?",
    "He will not come, will he?",
    "You are happy, aren't you?",
    "They did not call, did they?",
    "You are coming, aren't you?",
    "He does not play soccer, does he?",
    "She can sing, can't she?",
    "We are ready, aren't we?",
    "They do not like coffee, do they?",
    "You have seen it, haven't you?",
    "He likes books, doesn't he?",
    "She will not leave, will she?",
    "You are busy, aren't you?",
    "They did not go, did they?",
    "I like coffee, and so does she",
    "He does not play tennis, and neither do I",
    "She is tired, and so am I",
    "They do not eat meat, and neither do we",
    "I can swim, and so can he",
    "She did not go, and neither did I",
    "I am not ready, and neither is he",
    "I enjoy hiking, and so does he",
    "She does not watch TV, and neither do I",
    "He is happy, and so am I",
    "They do not travel much, and neither do we",
    "I can cook, and so can she",
    "He did not call, and neither did I",
    "I am not tired, and neither is she",
    "I enjoy reading books at night",
    "She decided not to join the club",
    "Would you like to watch a movie?",
    "He loves playing soccer with friends",
    "They do not want to leave early",
    "Do you prefer swimming or running?",
    "I hate waiting for buses",
    "She plans to study abroad",
    "Does he enjoy hiking in the mountains?",
    "We need to finish this project",
    "I like listening to music",
    "He decided not to buy the car",
    "Do you want to play tennis?",
    "She enjoys cooking for friends",
    "They do not like to wake up early",
    "Would you prefer dancing or singing?",
    "I hate cleaning the house",
    "He plans to visit London",
    "Does she like painting pictures?",
    "We need to write a report",
    "I used to live in a small town",
    "She did not use to like coffee",
    "Did you use to ride a bike?",
    "He used to play video games a lot",
    "They did not use to travel much",
    "Did we use to go to that park?",
    "I used to have a pet dog",
    "She did not use to read books",
    "Did he use to study here?",
    "We used to visit our grandparents often",
    "I used to watch cartoons every day",
    "He did not use to eat vegetables",
    "Did you use to live in a village?",
    "She used to play with dolls",
    "They did not use to go to the beach",
    "Did we use to play soccer together?",
    "I used to have long hair",
    "She did not use to like math",
    "Did he use to work here?",
    "We used to walk to school",
    "It might snow this evening",
    "She may not come to the party",
    "Could he be at the gym now?",
    "They might visit us tomorrow",
    "I may not finish this today",
    "Could it rain this afternoon?",
    "He might know the answer",
    "We may not go on vacation",
    "Could she be sick today?",
    "They might call later",
    "It might be cold tonight",
    "He may not like the gift",
    "Could they be at the library?",
    "She might join us for dinner",
    "I may not call him today",
    "Could it be sunny later?",
    "They might buy a new car",
    "We may not finish on time",
    "Could he be at the office?",
    "She might arrive late",
    "She said that she was happy",
    "He told me he did not like it",
    "Did she say where she was?",
    "They said they were coming",
    "I told him I was not ready",
    "Did he ask if we were free?",
    "She said that she loved the book",
    "He told us he did not know",
    "Did they say what time it was?",
    "I said I was tired",
    "He said that he was busy",
    "She told me she did not come",
    "Did you say why you were late?",
    "They said they liked the movie",
    "I told her I was not going",
    "Did she ask if we were ready?",
    "He said that he needed help",
    "They told us they did not see it",
    "Did he say where he went?",
    "She said she was hungry",
    "I have a few coins in my pocket",
    "There is little milk in the fridge",
    "Do you have a little sugar?",
    "She has few friends in this city",
    "We have a little time to rest",
    "Are there few people at the party?",
    "I have a few books to read",
    "There is little water in the glass",
    "Do you need a little help?",
    "He has few ideas for the project",
    "I have a few pens on my desk",
    "There is little coffee left",
    "Do you have a little money?",
    "She has few clothes to wear",
    "We have a little food in the kitchen",
    "Are there few students in class?",
    "I have a few tickets for the show",
    "There is little juice in the bottle",
    "Do you need a little advice?",
    "He has few hobbies",
    "If you mix blue and yellow, you get green",
    "Does water freeze if it is cold?",
    "If plants do not get water, they die",
    "Do you get wet if it rains?",
    "Does ice melt if it is hot?",
    "If you drop glass, it breaks",
    "Does wood burn if you light it?",
    "If you water plants, they grow",
    "I have just completed my essay",
    "She has not tried the new café yet",
    "Have you ever visited New York?",
    "They have already painted the room",
    "He has not finished his chores yet",
    "Have we ever discussed this topic?",
    "I have never watched that series",
    "She has just received a gift",
    "Haven't you seen the news yet?",
    "We have already ordered dinner",
    "They were dancing at the party last night",
    "She was not painting when I arrived",
    "Were you jogging in the park yesterday?",
    "He was fixing his bike all morning",
    "We were not chatting during the movie",
    "Was she knitting a scarf earlier?",
    "I was shopping when you called",
    "They were not swimming in the pool",
    "Were you writing a story last night?",
    "He was repairing the chair yesterday",
    "If it snows, we will build a snowman",
    "If you do not practice, you will not improve",
    "Will he join us if we call him?",
    "If we arrive early, we will get good seats",
    "She will not stay if she is tired",
    "Will they help if we ask them?",
    "If I study hard, I will pass the test",
    "He will not go if it is raining",
    "Will you come if I invite you?",
    "If we do not hurry, we will miss the show",
    "You should visit the new museum",
    "We must not forget the meeting time",
    "Do I have to submit this tomorrow?",
    "She should apologize to her friend",
    "He does not have to attend the party",
    "Must we complete this form now?",
    "You should try the new recipe",
    "They must not run in the classroom",
    "Does she have to leave early?",
    "I should check my emails",
    "Cars are faster now than before",
    "People do not use payphones anymore",
    "Is your school bigger now than it was?",
    "We watch TV less than we did",
    "She does not play outside as much as before",
    "Was travel slower in the past?",
    "Kids use tablets more than books now",
    "I do not visit the library as often as before",
    "Is life more expensive now than before?",
    "They communicate more online now",
    "The boy who paints well is my cousin",
    "The laptop that I bought is not working",
    "Which song do you sing?",
    "The cat which sleeps here is fluffy",
    "The woman who called was polite",
    "Is this the jacket that you lost?",
    "The coach who trains us is strict",
    "The camera that I want is pricey",
    "Who is the man that sells flowers?",
    "The park which we visited was crowded",
    "You are studying, aren't you?",
    "She does not eat spicy food, does she?",
    "He can skate, can't he?",
    "We are invited, aren't we?",
    "They do not like rain, do they?",
    "You have been here, haven't you?",
    "She loves dancing, doesn't she?",
    "He will not stay long, will he?",
    "You are early, aren't you?",
    "They did not forget, did they?",
    "I enjoy painting, and so does he",
    "She does not like jogging, and neither do I",
    "He is excited, and so am I",
    "They do not drink coffee, and neither do we",
    "I can dance, and so can she",
    "He did not study, and neither did I",
    "I am not hungry, and neither is she",
    "I love singing in the morning",
    "She decided not to attend the meeting",
    "Do you want to learn Spanish?",
    "He enjoys cycling on weekends",
    "They do not like to stay up late",
    "Would you prefer reading or writing?",
    "I hate doing chores on Sundays",
    "She plans to travel next year",
    "Does he enjoy playing chess?",
    "We need to clean the house",
    "I used to collect stamps as a kid",
    "She did not use to eat spicy food",
    "Did you use to swim every day?",
    "He used to watch movies every weekend",
    "They did not use to visit museums",
    "Did we use to play in that park?",
    "I used to wear glasses in school",
    "She did not use to like dancing",
    "Did he use to live in London?",
    "We used to go camping every summer",
    "It might get warm this afternoon",
    "She may not attend the concert",
    "Could he be at the café now?",
    "They might move to a new house",
    "I may not call her tonight",
    "Could it be cloudy later?",
    "He might like the new book",
    "We may not finish the project today",
    "Could she be at the park?",
    "They might arrive soon",
    "She said that she was excited",
    "He told me he did not understand",
    "Did she say why she was late?",
    "They said they were leaving early",
    "I told him I was not coming",
    "Did he ask if we were ready?",
    "She said that she needed help",
    "He told us he did not see it",
    "Did they say where they went?",
    "I said I was busy",
    "I have a few apples in the kitchen",
    "There is little time to prepare",
    "Do you have a little salt?",
    "She has few relatives in this town",
    "We have a little space in the car",
    "Are there few seats left?",
    "I have a few photos to share",
    "There is little bread on the table",
    "Do you need a little water?",
    "He has few plans for the weekend",
    "If you touch fire, you get burned",
    "If you do not drink water, you get thirsty",
    "Does paper tear if you pull it?",
    "If you exercise, you stay healthy",
    "If animals do not eat, they die",
    "Do you feel hot if it is sunny?",
    "If you do not charge your phone, it dies",
    "Does snow fall if it is cold?",
    "If you plant seeds, they grow",
    "I have just cleaned the kitchen",
    "She has not tried rock climbing yet",
    "Have you ever gone camping?",
    "They have already started the meeting",
    "He has not repaired his car yet",
    "Have we ever talked about this?",
    "I have never eaten spicy noodles",
    "She has just written an email",
    "Haven't you visited the zoo yet?",
    "We have already chosen a gift",
    "They were hiking in the forest yesterday",
    "She was not drawing when I saw her",
    "Were you gardening last evening?",
    "He was organizing his desk all day",
    "We were not eating lunch at noon",
    "Was she practicing the piano earlier?",
    "I was browsing the internet when you texted",
    "They were not exercising at the gym",
    "Were you painting the fence yesterday?",
    "He was washing dishes this morning",
    "If it is sunny, we will go hiking",
    "If you do not listen, you will not learn",
    "Will he stay if we invite him?",
    "If we book now, we will save money",
    "She will not join if she is busy",
    "Will they visit if we call them?",
    "If I work hard, I will get a raise",
    "He will not come if it is too late",
    "Will you help if I need you?",
    "If we do not leave soon, we will be late",
    "You should try the new coffee shop",
    "We must not miss the deadline",
    "Do I have to attend the meeting?",
    "She should rest after her trip",
    "He does not have to help today",
    "Must we bring our own food?",
    "You should update your phone",
    "They must not leave litter in the park",
    "Does she have to finish this now?",
    "I should organize my notes",
    "Homes are more modern now than before",
    "People do not send telegrams anymore",
    "Is your town safer now than it was?",
    "We shop online more than we did",
    "She does not ride horses as much as before",
    "Was school stricter in the past?",
    "Kids use phones more than toys now",
    "I do not cook as often as I did",
    "Is transport faster now than before?",
    "They meet friends in person less often now",
    "The student who studies hard is my friend",
    "The chair that I bought is broken",
    "Which picture did you draw?",
    "The bird which sings here is colorful",
    "The neighbor who helped us was kind",
    "Is this the bag that you forgot?",
    "The chef who cooks here is famous",
    "The watch that I like is expensive",
    "Who is the girl that plays the violin?",
    "The garden which we saw was beautiful",
    "You are hungry, aren't you?",
    "She does not drink tea, does she?",
    "He can cook, can't he?",
    "We are on time, aren't we?",
    "They do not play chess, do they?",
    "You have read this, haven't you?",
    "She loves music, doesn't she?",
    "He will not leave early, will he?",
    "You are relaxed, aren't you?",
    "They did not arrive, did they?",
    "I enjoy dancing, and so does she",
    "He does not like swimming, and neither do I",
    "She is nervous, and so am I",
    "They do not watch movies, and neither do we",
    "I can play chess, and so can he",
    "She did not travel, and neither did I",
    "I am not late, and neither is he",
    "I love painting landscapes on weekends",
    "She decided not to visit the museum",
    "Do you want to try skateboarding?",
    "He enjoys collecting rare coins",
    "They do not like to study late",
    "Would you prefer hiking or cycling?",
    "I hate washing the car",
    "She plans to learn Italian",
    "Does he enjoy writing stories?",
    "We need to repair the door",
    "I used to draw pictures every day",
    "She did not use to drink tea",
    "Did you use to climb trees?",
    "He used to listen to the radio often",
    "They did not use to eat out much",
    "Did we use to visit that café?",
    "I used to keep a diary",
    "She did not use to play sports",
    "Did he use to live in a village?",
    "We used to go fishing every summer",
    "It might be sunny this afternoon",
    "She may not finish her homework",
    "Could he be at the store now?",
    "They might travel abroad next month",
    "I may not watch the movie tonight",
    "Could it snow tomorrow?",
    "He might need some help",
    "We may not attend the event",
    "Could she be at the library?",
    "They might buy new furniture",
    "She said that she was ready",
    "He told me he did not agree",
    "Did she say how she felt?",
    "They said they were tired",
    "I told him I was not interested",
    "Did he ask if we were coming?",
    "She said that she loved the show",
    "He told us he did not understand",
    "Did they say when they arrived?",
    "I said I was late",
    "I have a few tickets for the concert",
    "There is little juice left in the jug",
    "Do you have a little butter?",
    "She has few hobbies to enjoy",
    "We have a little time to relax",
    "Are there few books on the shelf?",
    "I have a few ideas for the party",
    "There is little space in the room",
    "Do you need a little paint?",
    "He has few clothes to wear",
    "If you boil water, it evaporates",
    "Does glass break if you drop it?",
    "If you save energy, you help the planet",
    "If animals do not sleep, they get tired",
    "Do you sneeze if you catch a cold?",
    "If you study math, you understand numbers",
    "If you do not clean, things get dirty",
    "Does metal rust if it gets wet?",
    "If you feed birds, they come back",
    "I have just watered the plants",
    "She has not learned to drive yet",
    "Have you ever climbed a mountain?",
    "They have already sent the invitations",
    "He has not fixed his bike yet",
    "Have we ever gone to that festival?",
    "I have never ridden a horse",
    "She has just adopted a puppy",
    "Haven't you checked your messages yet?",
    "We have already packed our bags",
    "They were decorating the house yesterday",
    "She was not sewing when I visited",
    "Were you cycling in the park last night?",
    "He was planting flowers all morning",
    "We were not watching a show at 7 PM",
    "Was she baking cookies earlier?",
    "I was packing my suitcase when you called",
    "They were not dancing at the club",
    "Were you reading a magazine yesterday?",
    "He was fixing the lamp this afternoon",
    "If it is cold, we will wear jackets",
    "If you do not save money, you will not buy it",
    "Will he call if he is free?",
    "If we study now, we will be ready",
    "She will not go if it is too windy",
    "Will they stay if we prepare food?",
    "If I practice, I will get better",
    "He will not visit if he is tired",
    "Will you join if I call you?",
    "If we do not book soon, we will lose the deal",
    "You should try yoga for relaxation",
    "We must not leave the door unlocked",
    "Do I have to read this book?",
    "She should write a thank-you note",
    "He does not have to go to school today",
    "Must we arrive by 8 AM?",
    "You should watch this documentary",
    "They must not shout in the library",
    "Does she have to cook tonight?",
    "I should tidy my room soon",
    "Clothes are more colorful now than before",
    "People do not use maps as much now as before",
    "Is your village quieter now than it was?",
    "We listen to music online more now than before",
    "She does not knit sweaters like before",
    "Was shopping harder in the past?",
    "Kids watch videos more than they read now",
    "I do not play cards as often as I did",
    "Is technology better now than before?",
    "They exercise less now than in the past",
    "The teacher who explains well is my favorite",
    "The table that I chose is too big",
    "Which dress did you wear?",
    "The puppy which plays here is adorable",
    "The friend who visited us was funny",
    "Is this the pen that you lost?",
    "The artist who painted this is talented",
    "The phone which I ordered is new",
    "Who is the boy that rides a bike?",
    "The beach which we visited was clean",
    "You are excited, aren't you?",
    "She does not play the piano, does she?",
    "He can ride a bike, can't he?",
    "We are prepared, aren't we?",
    "They do not eat sweets, do they?",
    "You have traveled there, haven't you?",
    "She loves flowers, doesn't she?",
    "He will not be late, will he?",
    "You are ready, aren't you?",
    "They did not leave, did they?",
    "I enjoy gardening, and so does she",
    "He does not like cold weather, and neither do I",
    "She is bored, and so am I",
    "They do not read novels, and neither do we",
    "I can sing, and so can he",
    "She did not call, and neither did I",
    "I am not busy, and neither is he",
    "I love sketching in my free time",
    "She decided not to buy that dress",
    "Do you want to try surfing?",
    "He enjoys building model cars",
    "They do not like to wait long",
    "Would you prefer jogging or swimming?",
    "I hate folding clothes",
    "She plans to join a book club",
    "Does he enjoy taking photos?",
    "We need to fix the window",
    "I used to read comics every week",
    "She did not use to enjoy hiking",
    "Did you use to collect coins?",
    "He used to visit the park often",
    "They did not use to go camping",
    "Did we use to visit that museum?",
    "I used to have a pet fish",
    "She did not use to like spicy food",
    "Did he use to play the guitar?",
    "We used to go hiking every weekend",
    "It might be foggy tomorrow morning",
    "She may not like the new game",
    "Could he be at the museum now?",
    "They might plan a trip soon",
    "I may not visit them this week",
    "Could it get warmer later?",
    "He might enjoy the concert",
    "We may not stay for long",
    "Could she be at the office?",
    "They might paint the house soon",
    "She said that she was nervous",
    "He told me he did not want to go",
    "Did she say why she left early?",
    "They said they were studying",
    "I told him I was not free",
    "Did he ask if we were tired?",
    "She said that she liked the gift",
    "He told us he did not hear it",
    "Did they say how they felt?",
    "I said I was thirsty",
    "I have a few cookies in the jar",
    "There is little sugar in the bowl",
    "Do you have a little milk?",
    "She has few plans for the weekend",
    "We have a little room for guests",
    "Are there few chairs in the hall?",
    "I have a few postcards to send",
    "There is little ink in the printer",
    "Do you need a little advice?",
    "He has few tools for the job",
    "If you touch ice, it feels cold",
    "Does paper burn if you light it?",
    "If you eat healthy, you feel better",
    "If fish do not swim, they sink",
    "Do you sweat if it is hot?",
    "If you do not lock the door, it opens",
    "Does food cook if you heat it?",
    "If you care for pets, they stay happy",
    "I have just painted the fence",
    "She has not explored the new park yet",
    "Have you ever sailed on a boat?",
    "They have already decorated the hall",
    "He has not fixed his bike yet",
    "Have we ever attended that event?",
    "I have never tasted sushi",
    "She has just ordered a new jacket",
    "Haven't you updated your app yet?",
    "We have already reserved a table",
    "They were chatting at the café yesterday",
    "She was not knitting when I called",
    "Were you baking a cake last evening?",
    "He was arranging his books all morning",
    "We were not hiking in the forest yesterday",
    "Was she designing a poster earlier?",
    "I was cleaning the garage when it rained",
    "They were not jogging in the park",
    "Were you editing a video yesterday?",
    "He was feeding the cat this afternoon",
    "If it is warm, we will go swimming",
    "If you do not train, you will not win",
    "Will he help if we ask him?",
    "If we leave early, we will avoid traffic",
    "She will not stay if it is boring",
    "Will they join if we invite them?",
    "If I save enough, I will buy a laptop",
    "He will not go if it is too cold",
    "Will you call if I need you?",
    "If we do not plan, we will be late",
    "You should visit the art gallery",
    "We must not lose our tickets",
    "Do I have to complete this task?",
    "She should thank her teacher",
    "He does not have to drive today",
    "Must we wear uniforms tomorrow?",
    "You should try this new app",
    "They must not eat in the classroom",
    "Does she have to call him now?",
    "I should review my notes tonight",
    "Cities are noisier now than before",
    "People do not write diaries as much now as before",
    "Is your house bigger now than it was?",
    "We use apps more than we did",
    "She does not cycle to work anymore",
    "Was life calmer in the past?",
    "Kids play video games more than before",
    "I do not visit museums as often now as before",
    "Is travel easier now than before?",
    "They talk in person less often now than before",
    "The boy who writes poems is my friend",
    "The lamp that I bought is broken",
    "Which shirt do you like?",
    "The dog which barks here is small",
    "The neighbor who helped us was generous",
    "Is this the notebook that you lost?",
    "The writer who lives here is famous",
    "The tablet that I want is new",
    "Who is the girl that sings well?",
    "The forest which we explored was dense",
    "You are nervous, aren't you?",
    "She does not like cold drinks, does she?",
    "He can swim, can't he?",
    "We are early, aren't we?",
    "They do not play cards, do they?",
    "You have finished your meal, haven't you?",
    "She loves painting, doesn't she?",
    "He will not arrive late, will he?",
    "You are busy, aren't you?",
    "They did not call back, did they?",
    "I enjoy cycling, and so does he",
    "She does not like horror movies, and neither do I",
    "He is tired, and so am I",
    "They do not eat spicy food, and neither do we",
    "I can paint, and so can she",
    "She did not go shopping, and neither did I",
    "I am not sleepy, and neither is he",
    "I love hiking in the mountains",
    "She decided not to attend the party",
    "Do you want to learn coding?",
    "He enjoys fishing on weekends",
    "They do not like to get up early",
    "Would you prefer drawing or painting?",
    "I hate ironing clothes",
    "She plans to write a book",
    "Does he enjoy playing the piano?",
    "We need to paint the walls",
    "I used to play hide-and-seek as a kid",
    "She did not use to enjoy swimming",
    "Did you use to read fairy tales?",
    "He used to collect postcards",
    "They did not use to go camping",
    "Did we use to visit that museum?",
    "I used to have a pet fish",
    "She did not use to like spicy food",
    "Did he use to live near the beach?",
    "We used to watch stars at night",
    "It might rain this evening",
    "She may not join the club",
    "Could he be at the park now?",
    "They might redecorate their house",
    "I may not finish this book today",
    "Could it be sunny tomorrow?",
    "He might like the new song",
    "We may not go camping this weekend",
    "Could she be at the store?",
    "They might call us tonight",
    "She said that she was hungry",
    "He told me he did not like the plan",
    "Did she say where she went?",
    "They said they were excited",
    "I told him I was not ready yet",
    "Did he ask if we were busy?",
    "She said that she enjoyed the trip",
    "He told us he did not know the answer",
    "Did they say why they left?",
    "I said I was feeling fine",
    "I have a few pencils in my bag",
    "There is little coffee in the pot",
    "Do you have a little honey?",
    "She has few toys to play with",
    "We have a little time to chat",
    "Are there few tickets left?",
    "I have a few pictures to show",
    "There is little paint in the can",
    "Do you need a little sugar?",
    "He has few books to read",
    "If you heat butter, it melts",
    "Does water boil if you heat it?",
    "If you exercise daily, you stay fit",
    "If plants do not get light, they wilt",
    "Do you feel tired if you do not sleep?",
    "If you read a lot, you learn more",
    "Does ice form if it is freezing?",
    "If you water flowers, they bloom",
    "I have just baked a cake",
    "She has not joined the book club yet",
    "Have you ever flown in a helicopter?",
    "They have already tidied the room",
    "He has not painted the door yet",
    "Have we ever watched that play?",
    "I have never visited a castle",
    "She has just signed up for a course",
    "Haven't you cleaned the windows yet?",
    "We have already planned the party",
    "They were wrapping gifts yesterday",
    "She was not gardening when I arrived",
    "Were you sketching in the park last night?",
    "He was polishing his shoes all morning",
    "We were not playing games at 6 PM",
    "Was she folding laundry earlier?",
    "I was organizing my closet when you texted",
    "They were not cycling on the trail",
    "Were you practicing yoga yesterday?",
    "He was watering the lawn this afternoon",
    "If it is windy, we will fly kites",
    "If you do not rest, you will not recover",
    "Will he come if we text him?",
    "If we arrive on time, we will get tickets",
    "She will not visit if she is ill",
    "Will they stay if we cook dinner?",
    "If I work late, I will finish the project",
    "He will not join if it is raining",
    "Will you help if I call you?",
    "If we do not hurry, we will miss the train",
    "You should explore the new park",
    "We must not forget our homework",
    "Do I have to write a letter?",
    "She should call her cousin",
    "He does not have to attend the class",
    "Must we finish this by tonight?",
    "You should listen to this podcast",
    "They must not talk during the test",
    "Does she have to travel tomorrow?",
    "I should plan my weekend",
    "Schools are more modern now than before",
    "People do not use typewriters anymore",
    "Is your city cleaner now than it was?",
    "We watch movies online more now than before",
    "She does not bake cakes as much as before",
    "Was transport slower in the past?",
    "Kids use apps more than books now",
    "I do not write emails as often as I did",
    "Is food healthier now than before?",
    "They meet online more than in person now",
    "The girl who dances well is my sister",
    "The sofa that I bought is too small",
    "Which book did you read?",
    "The kitten which sleeps here is cute",
    "The man who visited us was friendly",
    "Is this the scarf that you knitted?",
    "The musician who plays here is talented",
    "The laptop which I ordered is fast",
    "Who is the boy that draws well?",
    "The lake which we saw was calm",
    "You are thirsty, aren't you?",
    "She does not like loud music, does she?",
    "He can play soccer, can't he?",
    "We are ready, aren't we?",
    "They do not watch TV, do they?",
    "You have seen this movie, haven't you?",
    "She loves chocolate, doesn't she?",
    "He will not stay, will he?",
    "You are calm, aren't you?",
    "They did not forget, did they?",
    "I enjoy baking, and so does he",
    "She does not like crowded places, and neither do I",
    "He is relaxed, and so am I",
    "They do not play video games, and neither do we",
    "I can draw, and so can she",
    "She did not visit, and neither did I",
    "I am not tired, and neither is she",
    "I love knitting scarves in winter",
    "She decided not to watch the show",
    "Do you want to try yoga?",
    "He enjoys planting trees",
    "They do not like to arrive late",
    "Would you prefer singing or dancing?",
    "I hate vacuuming the house",
    "She plans to visit Paris",
    "Does he enjoy collecting stamps?",
    "We need to decorate the room",
    "I used to build sandcastles as a child",
    "She did not use to like tea",
    "Did you use to play board games?",
    "He used to watch cartoons every day",
    "They did not use to travel often",
    "Did we use to eat at that café?",
    "I used to have a pet turtle",
    "She did not use to enjoy reading",
    "Did he use to live in the city?",
    "We used to go biking every Sunday",
    "It might get cold this evening",
    "She may not buy that dress",
    "Could he be at the cinema now?",
    "They might organize a party soon",
    "I may not call them today",
    "Could it rain later today?",
    "He might enjoy the new game",
    "We may not travel this month",
    "Could she be at the café?",
    "They might renovate their kitchen",
    "She said that she was tired",
    "He told me he did not want to wait",
    "Did she say why she was upset?",
    "They said they were happy",
    "I told him I was not going",
    "Did he ask if we were ready?",
    "She said that she loved the song",
    "He told us he did not see the show",
    "Did they say where they were?",
    "I said I was busy",
    "I have a few coins in my wallet",
    "There is little tea in the cup",
    "Do you have a little cream?",
    "She has few friends in this town",
    "We have a little space in the bag",
    "Are there few seats at the event?",
    "I have a few photos to print",
    "There is little oil in the bottle",
    "Do you need a little help?",
    "He has few plans for the holiday",
    "If you touch snow, it feels cold",
    "If you do not eat, you get hungry",
    "Does wood float if you put it in water?",
    "If you practice every day, you improve",
    "If plants do not get water, they die",
    "Do you feel warm if it is sunny?",
    "If you study hard, you pass exams",
    "If you do not clean, things get messy",
    "Does metal heat up if you burn it?",
    "If you feed animals, they stay healthy",
    "I have just organized my desk",
    "She has not tried yoga yet",
    "Have you ever swum in the ocean?",
    "They have already wrapped the presents",
    "He has not repaired the fence yet",
    "Have we ever been to that zoo?",
    "I have never seen a live concert",
    "She has just planted some flowers",
    "Haven't you booked the tickets yet?",
    "We have already cleaned the car",
    "They were shopping at the mall yesterday",
    "She was not writing a letter when I called",
    "Were you painting a picture last night?",
    "He was mowing the lawn all morning",
    "We were not watching movies at 8 PM",
    "Was she decorating the cake earlier?",
    "I was fixing my bike when you texted",
    "They were not walking in the park",
    "Were you playing chess yesterday?",
    "He was tidying the garage this afternoon",
    "If it is sunny, we will have a picnic",
    "If you do not practice, you will not succeed",
    "Will he join if we invite him?",
    "If we leave now, we will catch the flight",
    "She will not come if she is tired",
    "Will they help if we call them?",
    "If I study more, I will get good grades",
    "He will not stay if it is too noisy",
    "Will you visit if I text you?",
    "If we do not plan, we will miss the event",
    "You should visit the local market",
    "We must not leave the lights on",
    "Do I have to finish this report?",
    "She should thank her neighbor",
    "He does not have to clean today",
    "Must we submit this by tomorrow?",
    "You should try this new recipe",
    "They must not run in the hallway",
    "Does she have to work late?",
    "I should check my schedule",
    "Houses are more expensive now than before",
    "People do not use fax machines anymore",
    "Is your town busier now than it was?",
    "We listen to podcasts more than we did",
    "She does not sew clothes as much as before",
    "Was school harder in the past?",
    "Kids use laptops more than notebooks now",
    "I do not call friends as often as I did",
    "Is life faster now than before?",
    "They shop online more than in stores now",
    "The boy who plays chess is my classmate",
    "The desk that I bought is too heavy",
    "Which song do you like?",
    "The cat which lives here is playful",
    "The woman who helped us was kind",
    "Is this the book that you borrowed?",
    "The painter who works here is skilled",
    "The phone which I chose is modern",
    "Who is the boy that plays the drums?",
    "The river which we saw was clear",
    "You are happy, aren't you?",
    "She does not eat fish, does she?",
    "He can dance, can't he?",
    "We are on time, aren't we?",
    "They do not like hiking, do they?",
    "You have been to Paris, haven't you?",
    "She loves dancing, doesn't she?",
    "He will not arrive late, will he?",
    "You are relaxed, aren't you?",
    "They did not arrive late, did they?",
    "I enjoy swimming, and so does she",
    "He does not like spicy food, and neither do I",
    "She is excited, and so am I",
    "They do not eat meat, and neither do we",
    "I can cook, and so can he",
    "She did not travel, and neither did I",
    "I am not busy, and neither is he",
    "I love gardening on weekends",
    "She decided not to join the team",
    "Do you want to learn French?",
    "He enjoys playing board games",
    "They do not like to wake up early",
    "Would you prefer reading or watching TV?",
    "I hate cleaning windows",
    "She plans to start a blog",
    "Does he enjoy writing poems?",
    "We need to fix the roof",
    "I used to collect shells at the beach",
    "She did not use to like coffee",
    "Did you use to play soccer?",
    "He used to read magazines often",
    "They did not use to visit relatives much",
    "Did we use to go to that beach?",
    "I used to have a pet hamster",
    "She did not use to enjoy dancing",
    "Did he use to live in a small town?",
    "We used to go skating every winter",
    "It might snow this afternoon",
    "She may not attend the party",
    "Could he be at the library now?",
    "They might buy a new car soon",
    "I may not finish my homework today",
    "Could it be cloudy this evening?",
    "He might like the new movie",
    "We may not visit the museum",
    "Could she be at the gym?",
    "They might plan a vacation",
    "She said that she was cold",
    "He told me he did not like the book",
    "Did she say why she was late?",
    "They said they were busy",
    "I told him I was not hungry",
    "Did he ask if we were free?",
    "She said that she enjoyed the party",
    "He told us he did not know the way",
    "Did they say where they went?",
    "I said I was feeling tired",
    "I have a few stickers in my collection",
    "There is little water in the jug",
    "Do you have a little jam?",
    "She has few hobbies to enjoy",
    "We have a little time to prepare",
    "Are there few people at the event?",
    "I have a few letters to write",
    "There is little milk in the fridge",
    "Do you need a little paint?",
    "He has few tools to fix the car",
    "If you freeze water, it turns to ice",
    "If you do not sleep, you feel tired",
    "Does paper tear if you pull it hard?",
    "If you eat well, you stay healthy",
    "If animals do not eat, they get weak",
    "Do you feel cold if it is snowy?",
    "If you practice, you get better",
    "If you do not lock the gate, it opens",
    "Does food burn if you cook it too long?",
    "If you water plants, they grow well",
    "I have just rearranged the shelves",
    "She has not gone hiking yet",
    "Have you ever tried windsurfing?",
    "They have already painted the walls",
    "He has not fixed the computer yet",
    "Have we ever visited that museum?",
    "I have never seen a shooting star",
    "She has just enrolled in a dance class",
    "Haven't you packed your bag yet?",
    "We have already chosen a new sofa",
    "They were playing cards last evening",
    "She was not sketching when I arrived",
    "Were you repairing the car yesterday?",
    "He was sorting his clothes all morning",
    "We were not cooking dinner at 7 PM",
    "Was she sewing a dress earlier?",
    "I was watering the plants when you called",
    "They were not hiking on the trail",
    "Were you writing an email yesterday?",
    "He was cleaning the windows this afternoon",
    "If it is hot, we will go to the beach",
    "If you do not prepare, you will not win",
    "Will he visit if we call him?",
    "If we start now, we will finish early",
    "She will not stay if it is too crowded",
    "Will they come if we invite them?",
    "If I exercise, I will feel better",
    "He will not go if it is snowing",
    "Will you join if I ask you?",
    "If we do not leave now, we will be late",
    "You should try the new bakery",
    "We must not miss the bus",
    "Do I have to prepare a presentation?",
    "She should visit her aunt",
    "He does not have to clean today",
    "Must we submit this by tomorrow?",
    "You should read this article",
    "They must not leave trash outside",
    "Does she have to work late?",
    "I should update my calendar",
    "Life is more connected now than before",
    "People do not use pagers anymore",
    "Is your village smaller now than it was?",
    "We use smartphones more than we did",
    "She does not paint as much as before",
    "Was food fresher in the past?",
    "Kids play online games more now than before",
    "I do not visit the park as often as before",
    "Is transport safer now than before?",
    "They socialize in person less often now than before",
    "The girl who writes stories is my cousin",
    "The chair that I ordered is too big",
    "Which movie did you watch?",
    "The puppy which plays here is friendly",
    "The man who fixed our car was polite",
    "Is this the jacket that you bought?",
    "The singer who performs here is famous",
    "The tablet that I like is expensive",
    "Who is the boy that plays the drums?",
    "The park which we visited was green",
    "You are tired, aren't you?",
    "She does not drink coffee, does she?",
    "He can sing, can't he?",
    "We are late, aren't we?",
    "They do not like swimming, do they?",
    "You have been to Paris, haven't you?",
    "She loves dancing, doesn't she?",
    "He will not arrive late, will he?",
    "You are happy, aren't you?",
    "They did not leave early, did they?",
    "I enjoy reading novels, and so does she",
    "He does not like rainy days, and neither do I",
    "She is happy, and so am I",
    "They do not eat meat, and neither do we",
    "I can play the guitar, and so can he",
    "She did not go hiking, and neither did I",
    "I am not hungry, and neither is he",
    "I love dancing in the evenings",
    "She decided not to buy the shoes",
    "Do you want to try skiing?",
    "He enjoys collecting old coins",
    "They do not like to stay home",
    "Would you prefer jogging or cycling?",
    "I hate organizing my desk",
    "She plans to learn painting",
    "Does he enjoy playing cards?",
    "We need to clean the garden",
    "I used to play with toys as a child",
    "She did not use to eat vegetables",
    "Did you use to draw pictures?",
    "He used to listen to music every day",
    "They did not use to go to concerts",
    "Did we use to visit that lake?",
    "I used to have a pet parrot",
    "She did not use to like math",
    "Did he use to live in the countryside?",
    "We used to go swimming every summer",
    "It might be rainy this afternoon",
    "She may not come to the meeting",
    "Could he be at the bookstore now?",
    "They might adopt a pet soon",
    "I may not watch TV tonight",
    "Could it be warm tomorrow?",
    "He might enjoy the new book",
    "We may not go hiking this weekend",
    "Could she be at the market?",
    "They might repaint their room",
    "She said that she was excited",
    "He told me he did not like the movie",
    "Did she say why she was absent?",
    "They said they were ready",
    "I told him I was not tired",
    "Did he ask if we were coming?",
    "She said that she loved the play",
    "He told us he did not understand it",
    "Did they say where they were going?",
    "I said I was feeling good",
    "I have a few books in my bag",
    "There is little juice in the glass",
    "Do you have a little syrup?",
    "She has few clothes to wear",
    "We have a little time to shop",
    "Are there few tickets for the show?",
    "I have a few notes to share",
    "There is little tea in the pot",
    "Do you need a little help?",
    "He has few ideas for the event",
    "If you heat water, it boils",
    "If you do not drink, you get thirsty",
    "Does ice melt if you heat it?",
    "If animals do not rest, they get tired",
    "Do you feel hot if it is sunny?",
    "If you exercise, you stay strong",
    "If you do not clean, things get dirty",
    "Does metal rust if it gets wet?",
    "If you feed pets, they stay happy",
    "I have just washed the dishes",
    "She has not explored the new museum yet",
    "Have you ever gone scuba diving?",
    "They have already decorated the tree",
    "He has not repaired the lamp yet",
    "Have we ever attended that concert?",
    "I have never tried skateboarding",
    "She has just registered for a workshop",
    "Haven't you finished your essay yet?",
    "We have already planned our vacation",
    "They were cleaning the attic yesterday",
    "She was not painting the room when I called",
    "Were you jogging by the river last evening?",
    "He was fixing the chair all morning",
    "We were not watching TV at 9 PM",
    "Was she organizing her books earlier?",
    "I was sewing a blanket when you texted",
    "They were not playing soccer in the park",
    "Were you gardening yesterday afternoon?",
    "He was polishing the table this morning",
    "If it is rainy, we will stay indoors",
    "If you do not study, you will not pass the exam",
    "Will he stay if we invite him?",
    "If we book early, we will get a discount",
    "She will not come if she is busy",
    "Will they visit if we text them?",
    "If I save money, I will buy a new phone",
    "He will not go if it is too cold",
    "Will you help if I ask you?",
    "If we do not hurry, we will miss the bus",
    "You should visit the new zoo",
    "We must not forget our keys",
    "Do I have to submit this today?",
    "She should call her brother",
    "He does not have to attend the event",
    "Must we finish this by tomorrow?",
    "You should try this new game",
    "They must not leave their bags here",
    "Does she have to leave early?",
    "I should organize my schedule",
    "Life is busier now than it was before",
    "People do not use landlines much anymore",
    "Is your city safer now than in the past?",
    "We watch streaming services more now than before",
    "She does not knit blankets as much as before",
    "Was travel more difficult in the past?",
    "Kids use tablets more than they did",
    "I do not write letters as often as before",
    "Is food more expensive now than before?",
    "They meet friends online more now than before",
    "The boy who sings well is my neighbor",
    "The table that I ordered is too small",
    "Which book did you love?",
    "The dog which barks here is friendly",
    "The woman who visited us was kind",
    "Is this the pen that you dropped?",
    "The artist who paints here is creative",
    "The laptop which I bought is fast",
    "Who is the girl that plays chess?",
    "The garden which we saw was colorful",
    "You are excited, aren't you?",
    "She does not like tea, does she?",
    "He can play the piano, can't he?",
    "We are prepared, aren't you?",
    "They do not eat sweets, do they?",
    "You have seen this show, haven't you?",
    "She loves flowers, doesn't she?",
    "He will not arrive early, will he?",
    "You are calm, aren't you?",
    "They did not forget, did they?",
    "I enjoy hiking, and so does he",
    "She does not like cold weather, and neither do I",
    "He is tired, and so am I",
    "They do not watch movies, and neither do we",
    "I can sing, and so can she",
    "She did not go shopping, and neither did I",
    "I am not sleepy, and neither is he",
    "I love painting pictures on weekends",
    "She decided not to join the club",
    "Do you want to try dancing?",
    "He enjoys collecting postcards",
    "They do not like to be late",
    "Would you prefer swimming or jogging?",
    "I hate washing dishes",
    "She plans to learn Spanish",
    "Does he enjoy playing soccer?",
    "We need to repair the fence",
    "I used to collect coins as a kid",
    "She did not use to like spicy food",
    "Did you use to play hide-and-seek?",
    "He used to watch movies every night",
    "They did not use to visit museums",
    "Did we use to go to that park?",
    "I used to have a pet cat",
    "She did not use to enjoy swimming",
    "Did he use to live in a village?",
    "We used to go camping every summer",
    "It might be sunny this afternoon",
    "She may not attend the concert",
    "Could he be at the café now?",
    "They might buy a new sofa soon",
    "I may not finish this task today",
    "Could it rain this evening?",
    "He might like the new album",
    "We may not go to the party",
    "Could she be at the library?",
    "They might plan a trip soon",
    "She said that she was happy",
    "He told me he did not like the song",
    "Did she say why she was late?",
    "They said they were tired",
    "I told him I was not ready",
    "Did he ask if we were coming?",
    "She said that she loved the book",
    "He told us he did not know the answer",
    "Did they say where they went?",
    "I said I was feeling fine",
    "I have a few pens in my drawer",
    "There is little coffee in the jar",
    "Do you have a little sugar?",
    "She has few friends in this city",
    "We have a little time to relax",
    "Are there few seats at the concert?",
    "I have a few photos to share",
    "There is little water in the bottle",
    "Do you need a little help?",
    "He has few hobbies to enjoy",
    "If you touch fire, you get burned",
    "If you do not eat, you get hungry",
    "Does ice melt if it is warm?",
    "If animals do not drink, they get weak",
    "Do you feel cold if it is windy?",
    "If you do not clean, things get messy",
    "Does metal expand if you heat it?",
    "If you feed birds, they return",
    "I have just tidied the living room",
    "She has not visited the new gallery yet",
    "Have you ever tried horseback riding?",
    "They have already planned the wedding",
    "He has not fixed the chair yet",
    "Have we ever gone to that theater?",
    "I have never eaten vegan food",
    "She has just ordered new shoes",
    "Haven't you completed your project yet?",
    "We have already booked a hotel",
    "They were arranging flowers yesterday",
    "She was not writing a poem when I arrived",
    "Were you building a model last night?",
    "He was painting the door all morning",
    "We were not playing cards at 6 PM",
    "Was she knitting a hat earlier?",
    "I was washing the car when you called",
    "They were not swimming in the lake",
    "Were you editing photos yesterday?",
    "He was organizing his tools this afternoon",
    "If it is cloudy, we will stay home",
    "If you do not practice, you will not improve",
    "Will he join us if we ask him?",
    "If we leave early, we will avoid the rush",
    "She will not stay if it is too loud",
    "Will they come if we call them?",
    "If I save up, I will buy a camera",
    "He will not go if it is foggy",
    "Will you help if I need you?",
    "If we do not book now, we will miss out",
    "You should visit the new café",
    "We must not leave the gate open",
    "Do I have to write this essay?",
    "She should thank her friend",
    "He does not have to attend the party",
    "Must we complete this by tonight?",
    "You should try this new dish",
    "They must not play music loudly",
    "Does she have to leave now?",
    "I should review my homework",
    "Life is faster now than it was before",
    "People do not use floppy disks anymore",
    "Is your town greener now than in the past?",
    "We watch videos online more now than before",
    "She does not write poems as much as before",
    "Was school stricter in the past?",
    "Kids use phones more than books now",
    "I do not visit the library as often as before",
    "Is transport cheaper now than before?",
    "They socialize online more than in person now",
    "The boy who plays soccer is my friend",
    "The lamp that I bought is too bright",
    "Which song did you hear?",
    "The kitten which lives here is fluffy",
    "The neighbor who helped us was kind",
    "Is this the bag that you lost?",
    "The writer who lives here is talented",
    "The phone which I ordered is modern",
    "Who is the girl that dances well?",
    "The forest which we visited was peaceful",
    "You are hungry, aren't you?",
    "She does not like spicy food, does she?",
    "He can draw, can't he?",
    "We are ready, aren't we?",
    "They do not play chess, do they?",
    "You have seen this place, haven't you?",
    "She loves music, doesn't she?",
    "He will not leave early, will he?",
    "You are relaxed, aren't you?",
    "They did not arrive late, did they?",
    "I enjoy painting, and so does she",
    "He does not like loud music, and neither do I",
    "She is tired, and so am I",
    "They do not eat fish, and neither do we",
    "I can dance, and so can she",
    "She did not go to the party, and neither did I",
    "I am not nervous, and neither is he",
    "I love singing in the shower",
    "She decided not to attend the concert",
    "Do you want to try painting?",
    "He enjoys collecting stamps",
    "They do not like to arrive early",
    "Would you prefer reading or writing?",
    "I hate cleaning the kitchen",
    "She plans to learn Italian",
    "Does he enjoy playing the guitar?",
    "We need to fix the door",
    "I used to play marbles as a kid",
    "She did not use to eat sushi",
    "Did you use to read comics?",
    "He used to watch TV every evening",
    "They did not use to go hiking",
    "Did we use to visit that zoo?",
    "I used to have a pet rabbit",
    "She did not use to like dancing",
    "Did he use to live by the sea?",
    "We used to go fishing every weekend",
    "It might be cold this evening",
    "She may not join the team",
    "Could he be at the park now?",
    "They might buy a new laptop soon",
    "I may not watch the show tonight",
    "Could it snow later today?",
    "He might like the new song",
    "We may not go to the beach",
    "Could she be at the market?",
    "They might plan a barbecue soon",
    "She said that she was nervous",
    "He told me he did not like the plan",
    "Did she say why she was absent?",
    "They said they were happy",
    "I told him I was not tired",
    "Did he ask if we were ready?",
    "She said that she loved the book",
    "He told us he did not know the answer",
    "Did they say where they went?",
    "I said I was feeling fine",
    "I have a few postcards in my drawer",
    "There is little milk in the jug",
    "Do you have a little butter?",
    "She has few toys to play with",
    "We have a little time to chat",
    "Are there few chairs at the event?",
    "I have a few pictures to frame",
    "There is little juice in the bottle",
    "Do you need a little advice?",
    "He has few plans for the weekend",
    "If you touch ice, it feels cold",
    "If you do not rest, you get tired",
    "Does paper burn if you light it?",
    "If you exercise, you stay healthy",
    "If animals do not eat, they get weak",
    "Do you feel hot if it is sunny?",
    "If you do not lock the door, it opens",
    "Does metal rust if it gets wet?",
    "If you feed pets, they stay healthy",
    "I have just finished writing a letter",
    "She has not explored the new library yet",
    "Have you ever tried kayaking?",
    "They have already cleaned the house",
    "He has not repaired the clock yet",
    "Have we ever been to that festival?",
    "I have never watched a ballet show",
    "She has just signed up for a gym membership",
    "Haven't you finished your homework yet?",
    "We have already arranged a meeting",
    "They were decorating the room yesterday",
    "She was not baking bread when I called",
    "Were you walking the dog last evening?",
    "He was fixing the shelf all morning",
    "We were not watching a movie at 8 PM",
    "Was she arranging flowers earlier?",
    "I was tidying the kitchen when you texted",
    "They were not playing tennis in the park",
    "Were you drawing a picture yesterday?",
    "He was cleaning the garage this morning",
    "If it is warm, we will go camping",
    "If you do not study, you will not learn",
    "Will he come if we invite him?",
    "If we arrive early, we will get good seats",
    "She will not stay if it is too noisy",
    "Will they visit if we call them?",
    "If I work hard, I will earn more money",
    "He will not go if it is raining",
    "Will you join if I text you?",
    "If we do not plan, we will miss the concert",
    "You should try the new restaurant",
    "We must not leave the windows open",
    "Do I have to complete this form?",
    "She should visit her grandmother",
    "He does not have to attend the meeting",
    "Must we finish this by tomorrow?",
    "You should watch this new series",
    "They must not run in the classroom",
    "Does she have to work today?",
    "I should organize my bookshelf",
    "Life is more digital now than before",
    "People do not use phone booths anymore",
    "Is your city bigger now than in the past?",
    "We listen to music online more now than before",
    "She does not draw as much as before",
    "Was travel slower in the past?",
    "Kids use computers more than books now",
    "I do not visit relatives as often as before",
    "Is food fresher now than before?",
    "They meet online more than in person now",
    "The boy who plays the guitar is my friend",
    "The chair that I bought is too heavy",
    "Which movie did you enjoy?",
    "The puppy which sleeps here is adorable",
    "The woman who called us was polite",
    "Is this the notebook that you lost?",
    "The musician who performs here is skilled",
    "The tablet which I ordered is new",
    "Who is the girl that writes poems?",
    "The lake which we visited was beautiful",
    "You are thirsty, aren't you?",
    "She does not like coffee, does she?",
    "He can play chess, can't he?",
    "We are on time, aren't we?",
    "They do not eat spicy food, do they?",
    "You have been to London, haven't you?",
    "She loves painting, doesn't she?",
    "He will not be late, will he?",
    "You are happy, aren't you?",
    "They did not leave early, did they?",
    "I enjoy gardening, and so does he",
    "She does not like loud places, and neither do I",
    "He is excited, and so am I",
    "They do not watch TV, and neither do we",
    "I can dance, and so can she",
    "She did not go hiking, and neither did I",
    "I am not busy, and neither is he",
    "I love reading novels at night",
    "She decided not to attend the concert",
    "Do you want to try cycling?",
    "He enjoys collecting old books",
    "They do not like to wake up late",
    "Would you prefer dancing or singing?",
    "I hate washing the windows",
    "She plans to learn Italian",
    "Does he enjoy playing the piano?",
    "We need to clean the attic",
    "I used to play tag as a child",
    "She did not use to eat sushi",
    "Did you use to read comics?",
    "He used to watch cartoons every morning",
    "They did not use to visit parks",
    "Did we use to go to that café?",
    "I used to have a pet rabbit",
    "She did not use to like dancing",
    "Did he use to live in the city?",
    "We used to go biking every weekend",
    "It might be foggy this evening",
    "She may not come to the party",
    "Could he be at the gym now?",
    "They might buy a new table soon",
    "I may not finish this book tonight",
    "Could it snow this afternoon?",
    "He might like the new series",
    "We may not go to the beach",
    "Could she be at the market?",
    "They might plan a barbecue soon",
    "She said that she was cold",
    "He told me he did not like the show",
    "Did she say why she was late?",
    "They said they were happy",
    "I told him I was not tired",
    "Did he ask if we were ready?",
    "She said that she loved the book",
    "He told us he did not know the answer",
    "Did they say where they went?",
    "I said I was feeling fine",
    "I have a few coins in my pocket",
    "There is little tea in the kettle",
    "Do you have a little honey?",
    "She has few hobbies to enjoy",
    "We have a little time to rest",
    "Are there few tickets for the concert?",
    "I have a few photos to print",
    "There is little milk in the fridge",
    "Do you need a little advice?",
    "He has few plans for the holiday",
    "If you heat ice, it melts",
    "If you do not sleep, you get tired",
    "Does paper tear if you pull it?",
    "If you exercise, you stay fit",
    "If animals do not eat, they get weak",
    "Do you feel cold if it is snowy?",
    "If you do not lock the gate, it opens",
    "Does metal expand if you heat it?",
    "If you feed pets, they stay healthy"
  ]
};
