export const sortSentenceData = {
  "s": [
    "Although the lecture was challenging, the students took detailed notes.",
    "Successful language learners review mistakes and apply feedback consistently.",
    "The report suggests that online education can improve access significantly.",
    "People who practise daily tend to develop stronger speaking fluency.",
    "Liam doesn't like spicy food, and neither do you.",
    "Sophia doesn't like spicy food, and neither does Liam.",
    "Emma enjoyed the film, and so did John.",
    "Olivia enjoyed the film, and so did Liam.",
    "Jack enjoyed the film, and so did I.",
    "If Emma had studied more, she would have passed the exam.",
    "If Emily had known the truth, she would have reacted differently.",
    "If John were more organized, Sophia would have finished on time.",
    "If Sophia had studied more, she would have passed the exam.",
    "If they were more organized, you would have finished on time.",
    "Jack doesn't like spicy food, and neither does Olivia.",
    "Olivia doesn't like spicy food, and neither do they.",
    "It doesn't like spicy food, and neither do we.",
    "Olivia doesn't like spicy food, and neither does he.",
    "Liam enjoyed the film, and so did Lucas.",
    "I enjoyed the film, and so did Emma.",
    "Emma enjoyed the film, and so did I.",
    "If Sophia were more organized, you would have finished on time.",
    "If Sophia had studied more, Emma would have passed the exam.",
    "Had Emma been more careful, she wouldn't have lost her keys.",
    "Not only did Liam finish the project, but he also helped his team.",
    "Rarely have I seen such a well-prepared presentation.",
    "If Sophia had arrived on time, the meeting could have started earlier.",
    "Neither Jack nor Olivia enjoys crowded places.",
    "Should you need assistance, don't hesitate to ask.",
    "No sooner had John left the room than the phone rang.",
    "If I were to choose, I'd prefer working remotely.",
    "Under no circumstances would Emma agree to that proposal.",
    "Had Lucas known the schedule, he wouldn't have been late.",
    "Not until Sophia explained the issue did I understand it fully.",
    "If only Olivia had listened to the advice, she'd be better off now.",
    "Seldom does Jack miss a deadline.",
    "If Liam had taken the earlier flight, he could be home by now.",
    "Never have I encountered such a challenging task.",
    "Were Emily to apologize, the conflict might be resolved.",
    "Only after the exam did Sophia realize her mistake.",
    "If John hadn't overslept, he would have caught the bus.",
    "Hardly had Olivia started speaking when the audience applauded.",
    "Should Emma decide to join, the team would benefit greatly.",
    "If I had saved more last year, I could afford a new car now.",
    "No matter how hard Lucas tries, he can't solve that puzzle.",
    "If Sophia were less impulsive, she'd make better decisions.",
    "Rarely does Emily forget her appointments.",
    "Had Jack prepared thoroughly, he would have passed the interview.",
    "Not only is Olivia talented, but she's also very hardworking.",
    "If Liam had checked the map, he wouldn't have gotten lost.",
    "Under no circumstances should you share confidential information.",
    "Seldom have I met someone as kind as Sophia.",
    "If only John had studied harder, he'd be at university now.",
    "No sooner had Emma arrived than the rain started.",
    "Were Lucas to take the lead, the project might succeed.",
    "If Olivia hadn't missed the deadline, she'd still have the contract.",
    "Hardly had Sophia finished her speech when the crowd cheered.",
    "Should Emily need help, I'm always available.",
    "If Jack had been more patient, he could have avoided the argument.",
    "Never would Liam admit to making a mistake.",
    "If I were in Sophia's position, I'd take the opportunity.",
    "Only when Olivia apologized did the tension ease.",
    "Had John been more attentive, he wouldn't have failed the test.",
    "Not until Emma arrived did the party really start.",
    "If Lucas had planned better, the trip would have been smoother.",
    "Seldom does Sophia lose her temper.",
    "If Emily had trusted her instincts, she'd have made the right choice.",
    "No matter what Jack says, Olivia won't change her mind.",
    "Were Liam to reconsider, he might accept the offer.",
    "If only Sophia had checked her email, she'd have seen the update.",
    "Hardly had John left the office when the news broke.",
    "Should Olivia want to join, we'd welcome her warmly.",
    "If Emma had been more organized, she'd have finished on time.",
    "Never have I witnessed such a dramatic turnaround.",
    "If Jack were more reliable, the team would trust him more.",
    "Rarely does Lucas miss an opportunity to learn.",
    "Had Sophia taken the advice, she could have avoided trouble.",
    "Not only did Emily excel in her role, but she also inspired others.",
    "If John had listened carefully, he wouldn't have misunderstood.",
    "Under no circumstances would Olivia compromise her values.",
    "Seldom have I seen such dedication in a team.",
    "If Liam had been more proactive, he'd have secured the deal.",
    "No sooner had Sophia entered than everyone greeted her.",
    "Were Emma to try again, she might succeed.",
    "If Jack hadn't hesitated, he could have won the competition.",
    "Only after Lucas explained did I grasp the concept.",
    "Had Olivia been more prepared, she'd have aced the presentation.",
    "If Sophia were to relocate, she'd find better opportunities.",
    "Hardly had Emily started when the system crashed.",
    "Should John need guidance, I'd be happy to assist.",
    "If Liam had avoided distractions, he'd have finished earlier.",
    "Never would Sophia ignore a friend in need.",
    "If only Emma had practiced more, she'd have performed better.",
    "Rarely does Olivia make the same mistake twice.",
    "If Rowan hadn't rushed, he'd have done better.",
    "Hardly had Tessa finished when the client responded.",
    "Should Aria reconsider, we'd be glad to have her back."
  ]
};
